// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.synthetics;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.newrelic.Utilities;
import com.pulumi.newrelic.synthetics.MultiLocationAlertConditionArgs;
import com.pulumi.newrelic.synthetics.inputs.MultiLocationAlertConditionState;
import com.pulumi.newrelic.synthetics.outputs.MultiLocationAlertConditionCritical;
import com.pulumi.newrelic.synthetics.outputs.MultiLocationAlertConditionWarning;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Use this resource to create, update, and delete a New Relic Synthetics Location Alerts.
 * 
 * &gt; **NOTE:** This is a legacy resource. The newrelic.NrqlAlertCondition resource is preferred for configuring alerts conditions. In most cases feature parity can be achieved with a NRQL query. This condition type may be deprecated in the future.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.newrelic.AlertPolicy;
 * import com.pulumi.newrelic.AlertPolicyArgs;
 * import com.pulumi.newrelic.synthetics.Monitor;
 * import com.pulumi.newrelic.synthetics.MonitorArgs;
 * import com.pulumi.newrelic.synthetics.MultiLocationAlertCondition;
 * import com.pulumi.newrelic.synthetics.MultiLocationAlertConditionArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MultiLocationAlertConditionCriticalArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MultiLocationAlertConditionWarningArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var policy = new AlertPolicy(&#34;policy&#34;, AlertPolicyArgs.builder()        
 *             .name(&#34;my-policy&#34;)
 *             .build());
 * 
 *         var monitor = new Monitor(&#34;monitor&#34;, MonitorArgs.builder()        
 *             .locationsPublics(&#34;US_WEST_1&#34;)
 *             .name(&#34;my-monitor&#34;)
 *             .period(&#34;EVERY_10_MINUTES&#34;)
 *             .status(&#34;DISABLED&#34;)
 *             .type(&#34;SIMPLE&#34;)
 *             .uri(&#34;https://www.one.newrelic.com&#34;)
 *             .build());
 * 
 *         var example = new MultiLocationAlertCondition(&#34;example&#34;, MultiLocationAlertConditionArgs.builder()        
 *             .policyId(policy.id())
 *             .name(&#34;Example condition&#34;)
 *             .runbookUrl(&#34;https://example.com&#34;)
 *             .enabled(true)
 *             .violationTimeLimitSeconds(3600)
 *             .entities(monitor.id())
 *             .critical(MultiLocationAlertConditionCriticalArgs.builder()
 *                 .threshold(2)
 *                 .build())
 *             .warning(MultiLocationAlertConditionWarningArgs.builder()
 *                 .threshold(1)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * ## Tags
 * 
 * Manage synthetics multilocation alert condition tags with `newrelic.EntityTags`. For up-to-date documentation about the tagging resource, please check newrelic.EntityTags
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.newrelic.AlertPolicy;
 * import com.pulumi.newrelic.AlertPolicyArgs;
 * import com.pulumi.newrelic.synthetics.Monitor;
 * import com.pulumi.newrelic.synthetics.MonitorArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MonitorCustomHeaderArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MonitorTagArgs;
 * import com.pulumi.newrelic.synthetics.MultiLocationAlertCondition;
 * import com.pulumi.newrelic.synthetics.MultiLocationAlertConditionArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MultiLocationAlertConditionCriticalArgs;
 * import com.pulumi.newrelic.synthetics.inputs.MultiLocationAlertConditionWarningArgs;
 * import com.pulumi.newrelic.EntityTags;
 * import com.pulumi.newrelic.EntityTagsArgs;
 * import com.pulumi.newrelic.inputs.EntityTagsTagArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var foo = new AlertPolicy(&#34;foo&#34;, AlertPolicyArgs.builder()        
 *             .name(&#34;foo policy&#34;)
 *             .build());
 * 
 *         var fooMonitor = new Monitor(&#34;fooMonitor&#34;, MonitorArgs.builder()        
 *             .status(&#34;ENABLED&#34;)
 *             .name(&#34;foo monitor&#34;)
 *             .period(&#34;EVERY_MINUTE&#34;)
 *             .uri(&#34;https://www.one.newrelic.com&#34;)
 *             .type(&#34;SIMPLE&#34;)
 *             .locationsPublics(&#34;AP_EAST_1&#34;)
 *             .customHeaders(MonitorCustomHeaderArgs.builder()
 *                 .name(&#34;some_name&#34;)
 *                 .value(&#34;some_value&#34;)
 *                 .build())
 *             .treatRedirectAsFailure(true)
 *             .validationString(&#34;success&#34;)
 *             .bypassHeadRequest(true)
 *             .verifySsl(true)
 *             .tags(MonitorTagArgs.builder()
 *                 .key(&#34;some_key&#34;)
 *                 .values(&#34;some_value&#34;)
 *                 .build())
 *             .build());
 * 
 *         var fooMultiLocationAlertCondition = new MultiLocationAlertCondition(&#34;fooMultiLocationAlertCondition&#34;, MultiLocationAlertConditionArgs.builder()        
 *             .policyId(foo.id())
 *             .name(&#34;foo condition&#34;)
 *             .runbookUrl(&#34;https://example.com&#34;)
 *             .enabled(true)
 *             .violationTimeLimitSeconds(3600)
 *             .entities(fooMonitor.id())
 *             .critical(MultiLocationAlertConditionCriticalArgs.builder()
 *                 .threshold(2)
 *                 .build())
 *             .warning(MultiLocationAlertConditionWarningArgs.builder()
 *                 .threshold(1)
 *                 .build())
 *             .build());
 * 
 *         var myConditionEntityTags = new EntityTags(&#34;myConditionEntityTags&#34;, EntityTagsArgs.builder()        
 *             .guid(fooMultiLocationAlertCondition.entityGuid())
 *             .tags(            
 *                 EntityTagsTagArgs.builder()
 *                     .key(&#34;my-key&#34;)
 *                     .values(                    
 *                         &#34;my-value&#34;,
 *                         &#34;my-other-value&#34;)
 *                     .build(),
 *                 EntityTagsTagArgs.builder()
 *                     .key(&#34;my-key-2&#34;)
 *                     .values(&#34;my-value-2&#34;)
 *                     .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * New Relic Synthetics MultiLocation Conditions can be imported using a concatenated string of the format
 * 
 *  `&lt;policy_id&gt;:&lt;condition_id&gt;`, e.g.
 * 
 * bash
 * 
 * ```sh
 * $ pulumi import newrelic:synthetics/multiLocationAlertCondition:MultiLocationAlertCondition example 12345678:1456
 * ```
 * 
 */
@ResourceType(type="newrelic:synthetics/multiLocationAlertCondition:MultiLocationAlertCondition")
public class MultiLocationAlertCondition extends com.pulumi.resources.CustomResource {
    /**
     * A condition term with priority set to critical.
     * 
     */
    @Export(name="critical", refs={MultiLocationAlertConditionCritical.class}, tree="[0]")
    private Output<MultiLocationAlertConditionCritical> critical;

    /**
     * @return A condition term with priority set to critical.
     * 
     */
    public Output<MultiLocationAlertConditionCritical> critical() {
        return this.critical;
    }
    /**
     * Set whether to enable the alert condition. Defaults to true.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enabled;

    /**
     * @return Set whether to enable the alert condition. Defaults to true.
     * 
     */
    public Output<Optional<Boolean>> enabled() {
        return Codegen.optional(this.enabled);
    }
    /**
     * The GUIDs of the Synthetics monitors to alert on.
     * 
     */
    @Export(name="entities", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> entities;

    /**
     * @return The GUIDs of the Synthetics monitors to alert on.
     * 
     */
    public Output<List<String>> entities() {
        return this.entities;
    }
    /**
     * The unique entity identifier of the condition in New Relic.
     * 
     */
    @Export(name="entityGuid", refs={String.class}, tree="[0]")
    private Output<String> entityGuid;

    /**
     * @return The unique entity identifier of the condition in New Relic.
     * 
     */
    public Output<String> entityGuid() {
        return this.entityGuid;
    }
    /**
     * The title of this condition.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The title of this condition.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The ID of the policy where this condition will be used.
     * 
     */
    @Export(name="policyId", refs={Integer.class}, tree="[0]")
    private Output<Integer> policyId;

    /**
     * @return The ID of the policy where this condition will be used.
     * 
     */
    public Output<Integer> policyId() {
        return this.policyId;
    }
    /**
     * Runbook URL to display in notifications.
     * 
     */
    @Export(name="runbookUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> runbookUrl;

    /**
     * @return Runbook URL to display in notifications.
     * 
     */
    public Output<Optional<String>> runbookUrl() {
        return Codegen.optional(this.runbookUrl);
    }
    /**
     * Sets a time limit, in seconds, that will automatically force-close a long-lasting incident after the time limit you
     * select. Must be in the range of 300 to 2592000 (inclusive)
     * 
     */
    @Export(name="violationTimeLimitSeconds", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> violationTimeLimitSeconds;

    /**
     * @return Sets a time limit, in seconds, that will automatically force-close a long-lasting incident after the time limit you
     * select. Must be in the range of 300 to 2592000 (inclusive)
     * 
     */
    public Output<Optional<Integer>> violationTimeLimitSeconds() {
        return Codegen.optional(this.violationTimeLimitSeconds);
    }
    /**
     * A condition term with priority set to warning.
     * 
     */
    @Export(name="warning", refs={MultiLocationAlertConditionWarning.class}, tree="[0]")
    private Output</* @Nullable */ MultiLocationAlertConditionWarning> warning;

    /**
     * @return A condition term with priority set to warning.
     * 
     */
    public Output<Optional<MultiLocationAlertConditionWarning>> warning() {
        return Codegen.optional(this.warning);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public MultiLocationAlertCondition(String name) {
        this(name, MultiLocationAlertConditionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public MultiLocationAlertCondition(String name, MultiLocationAlertConditionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public MultiLocationAlertCondition(String name, MultiLocationAlertConditionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("newrelic:synthetics/multiLocationAlertCondition:MultiLocationAlertCondition", name, args == null ? MultiLocationAlertConditionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private MultiLocationAlertCondition(String name, Output<String> id, @Nullable MultiLocationAlertConditionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("newrelic:synthetics/multiLocationAlertCondition:MultiLocationAlertCondition", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static MultiLocationAlertCondition get(String name, Output<String> id, @Nullable MultiLocationAlertConditionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new MultiLocationAlertCondition(name, id, state, options);
    }
}
