// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.newrelic.FleetConfigurationArgs;
import com.pulumi.newrelic.Utilities;
import com.pulumi.newrelic.inputs.FleetConfigurationState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Use this resource to create and manage New Relic fleet configurations for centralized agent management.
 * 
 * A fleet configuration holds versioned agent settings. The configuration content is immutable — each change to `configurationContent` creates a new version on the API automatically, similar to how AWS launch templates work. The resource ID (the configuration entity GUID) never changes across updates. Use the `newrelic.FleetConfiguration` data source to access the content of a specific historical version.
 * 
 * ## Example Usage
 * 
 * ### Basic Infrastructure Agent Configuration
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.newrelic.FleetConfiguration;
 * import com.pulumi.newrelic.FleetConfigurationArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var infra = new FleetConfiguration("infra", FleetConfigurationArgs.builder()
 *             .name("Production Infrastructure Config")
 *             .agentType("NRInfra")
 *             .managedEntityType("HOST")
 *             .operatingSystem("LINUX")
 *             .configurationContent("""
 * log:
 *   level: info
 *   file: /var/log/newrelic-infra/newrelic-infra.log
 * metrics:
 *   enabled: true
 *   system_sample_rate: 15
 *             """)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Out-of-band drift warnings
 * 
 * If a version is deleted outside of Terraform (UI, API, or another tool), the next `plan` or `refresh` will surface a warning so you understand why state changed:
 * 
 * If the previously-tracked **latest** version was the one deleted, an additional, stronger warning fires explaining that `configurationContent` has been refreshed from the new latest version on the API. If your declared content differs from that new latest, the next `apply` will create a new version restoring your declared content — this is the expected, self-healing behavior.
 * 
 * ## Import
 * 
 * Fleet configurations can be imported using a composite ID of `&lt;configuration_guid&gt;:&lt;managed_entity_type&gt;`:
 * 
 * ```sh
 * $ pulumi import newrelic:index/fleetConfiguration:FleetConfiguration infra &lt;configuration_guid&gt;:HOST
 * $ pulumi import newrelic:index/fleetConfiguration:FleetConfiguration infra &lt;configuration_guid&gt;:KUBERNETESCLUSTER
 * ```
 * 
 * The `managedEntityType` portion is required because the New Relic API does not return it via the entity lookup query (a GraphQL schema constraint). All other attributes — `name`, `agentType`, `operatingSystem`, `organizationId`, `configurationContent` — are resolved automatically from the API.
 * 
 */
@ResourceType(type="newrelic:index/fleetConfiguration:FleetConfiguration")
public class FleetConfiguration extends com.pulumi.resources.CustomResource {
    /**
     * The type of agent this configuration is for. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`. **Cannot be changed after creation.**
     * 
     */
    @Export(name="agentType", refs={String.class}, tree="[0]")
    private Output<String> agentType;

    /**
     * @return The type of agent this configuration is for. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`. **Cannot be changed after creation.**
     * 
     */
    public Output<String> agentType() {
        return this.agentType;
    }
    /**
     * The YAML or JSON content for this configuration. Use `file()` to load content from a file. Each change to this field creates a new immutable version on the API; the resource ID remains constant.
     * 
     */
    @Export(name="configurationContent", refs={String.class}, tree="[0]")
    private Output<String> configurationContent;

    /**
     * @return The YAML or JSON content for this configuration. Use `file()` to load content from a file. Each change to this field creates a new immutable version on the API; the resource ID remains constant.
     * 
     */
    public Output<String> configurationContent() {
        return this.configurationContent;
    }
    /**
     * The entity GUID of the configuration.
     * 
     */
    @Export(name="configurationId", refs={String.class}, tree="[0]")
    private Output<String> configurationId;

    /**
     * @return The entity GUID of the configuration.
     * 
     */
    public Output<String> configurationId() {
        return this.configurationId;
    }
    /**
     * The entity GUID of the highest-numbered version.
     * 
     */
    @Export(name="latestVersionEntityId", refs={String.class}, tree="[0]")
    private Output<String> latestVersionEntityId;

    /**
     * @return The entity GUID of the highest-numbered version.
     * 
     */
    public Output<String> latestVersionEntityId() {
        return this.latestVersionEntityId;
    }
    /**
     * The highest version number across all versions created so far.
     * 
     */
    @Export(name="latestVersionNumber", refs={Integer.class}, tree="[0]")
    private Output<Integer> latestVersionNumber;

    /**
     * @return The highest version number across all versions created so far.
     * 
     */
    public Output<Integer> latestVersionNumber() {
        return this.latestVersionNumber;
    }
    /**
     * The type of entities this configuration manages. Valid values: `HOST`, `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     * 
     */
    @Export(name="managedEntityType", refs={String.class}, tree="[0]")
    private Output<String> managedEntityType;

    /**
     * @return The type of entities this configuration manages. Valid values: `HOST`, `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     * 
     */
    public Output<String> managedEntityType() {
        return this.managedEntityType;
    }
    /**
     * The name of the configuration. **Changing this forces resource recreation** — the API does not support renaming a configuration in place.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the configuration. **Changing this forces resource recreation** — the API does not support renaming a configuration in place.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The operating system this configuration targets. Valid values: `LINUX`, `WINDOWS`. Applicable to `HOST` configurations only — must not be set when `managedEntityType` is `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     * 
     */
    @Export(name="operatingSystem", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> operatingSystem;

    /**
     * @return The operating system this configuration targets. Valid values: `LINUX`, `WINDOWS`. Applicable to `HOST` configurations only — must not be set when `managedEntityType` is `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     * 
     */
    public Output<Optional<String>> operatingSystem() {
        return Codegen.optional(this.operatingSystem);
    }
    /**
     * The organization ID. Auto-fetched from the account when not provided. **Cannot be changed after creation.**
     * 
     */
    @Export(name="organizationId", refs={String.class}, tree="[0]")
    private Output<String> organizationId;

    /**
     * @return The organization ID. Auto-fetched from the account when not provided. **Cannot be changed after creation.**
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }
    /**
     * Total number of versions currently in the configuration.
     * 
     */
    @Export(name="totalVersions", refs={Integer.class}, tree="[0]")
    private Output<Integer> totalVersions;

    /**
     * @return Total number of versions currently in the configuration.
     * 
     */
    public Output<Integer> totalVersions() {
        return this.totalVersions;
    }
    /**
     * A list of entity GUIDs for all versions, sorted oldest-first. Use with the `newrelic.FleetConfiguration` data source to retrieve the content of a specific historical version.
     * 
     */
    @Export(name="versionEntityIds", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> versionEntityIds;

    /**
     * @return A list of entity GUIDs for all versions, sorted oldest-first. Use with the `newrelic.FleetConfiguration` data source to retrieve the content of a specific historical version.
     * 
     */
    public Output<List<String>> versionEntityIds() {
        return this.versionEntityIds;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FleetConfiguration(java.lang.String name) {
        this(name, FleetConfigurationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FleetConfiguration(java.lang.String name, FleetConfigurationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FleetConfiguration(java.lang.String name, FleetConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("newrelic:index/fleetConfiguration:FleetConfiguration", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private FleetConfiguration(java.lang.String name, Output<java.lang.String> id, @Nullable FleetConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("newrelic:index/fleetConfiguration:FleetConfiguration", name, state, makeResourceOptions(options, id), false);
    }

    private static FleetConfigurationArgs makeArgs(FleetConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? FleetConfigurationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FleetConfiguration get(java.lang.String name, Output<java.lang.String> id, @Nullable FleetConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FleetConfiguration(name, id, state, options);
    }
}
