// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.plugins;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.newrelic.Utilities;
import com.pulumi.newrelic.plugins.inputs.GetPluginArgs;
import com.pulumi.newrelic.plugins.inputs.GetPluginComponentArgs;
import com.pulumi.newrelic.plugins.inputs.GetPluginComponentPlainArgs;
import com.pulumi.newrelic.plugins.inputs.GetPluginPlainArgs;
import com.pulumi.newrelic.plugins.outputs.GetPluginComponentResult;
import com.pulumi.newrelic.plugins.outputs.GetPluginResult;
import java.util.concurrent.CompletableFuture;

public final class PluginsFunctions {
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static Output<GetPluginResult> getPlugin(GetPluginArgs args) {
        return getPlugin(args, InvokeOptions.Empty);
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static CompletableFuture<GetPluginResult> getPluginPlain(GetPluginPlainArgs args) {
        return getPluginPlain(args, InvokeOptions.Empty);
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static Output<GetPluginResult> getPlugin(GetPluginArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("newrelic:plugins/getPlugin:getPlugin", TypeShape.of(GetPluginResult.class), args, Utilities.withVersion(options));
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static CompletableFuture<GetPluginResult> getPluginPlain(GetPluginPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("newrelic:plugins/getPlugin:getPlugin", TypeShape.of(GetPluginResult.class), args, Utilities.withVersion(options));
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static Output<GetPluginComponentResult> getPluginComponent(GetPluginComponentArgs args) {
        return getPluginComponent(args, InvokeOptions.Empty);
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static CompletableFuture<GetPluginComponentResult> getPluginComponentPlain(GetPluginComponentPlainArgs args) {
        return getPluginComponentPlain(args, InvokeOptions.Empty);
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static Output<GetPluginComponentResult> getPluginComponent(GetPluginComponentArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("newrelic:plugins/getPluginComponent:getPluginComponent", TypeShape.of(GetPluginComponentResult.class), args, Utilities.withVersion(options));
    }
    /**
     * New Relic Plugins reached end of life Wednesday June 16, 2021.
     * 
     * **This data source has been removed.**
     * 
     * For more information, [click here](https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267)
     * 
     */
    public static CompletableFuture<GetPluginComponentResult> getPluginComponentPlain(GetPluginComponentPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("newrelic:plugins/getPluginComponent:getPluginComponent", TypeShape.of(GetPluginComponentResult.class), args, Utilities.withVersion(options));
    }
}
