// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic
{
    /// <summary>
    /// Use this resource to create and manage New Relic notification destinations. Details regarding supported products and permissions can be found [here](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/destinations).
    /// 
    /// ## Example Usage
    /// 
    /// ##### [Webhook](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#webhook)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "foo",
    ///         Type = "WEBHOOK",
    ///         SecureUrl = new NewRelic.Inputs.NotificationDestinationSecureUrlArgs
    ///         {
    ///             Prefix = "https://webhook.mywebhook.com/",
    ///             SecureSuffix = "service_id/123456",
    ///         },
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "source",
    ///                 Value = "terraform",
    ///             },
    ///         },
    ///         AuthCustomHeaders = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationAuthCustomHeaderArgs
    ///             {
    ///                 Key = "API_KEY",
    ///                 Value = "test-api-key",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// See additional examples.
    /// 
    /// ## Additional Examples
    /// 
    /// &gt; **NOTE:** We support all properties. The mentioned properties are just an example.
    /// 
    /// #### [WORKFLOW_AUTOMATION]
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "workflow-automation-destination-name",
    ///         Type = "WORKFLOW_AUTOMATION",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "",
    ///                 Value = "",
    ///             },
    ///         },
    ///         AuthCustomHeaders = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationAuthCustomHeaderArgs
    ///             {
    ///                 Key = "Api-Key",
    ///                 Value = "YOUR_NR_USER_API_KEY",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [MICROSOFT_TEAMS](https://docs.newrelic.com/docs/alerts/get-notified/microsoft-teams-integrations/)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "ms-teams-example",
    ///         Type = "MICROSOFT_TEAMS",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "securityCode",
    ///                 Value = "abcdefgh",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [ServiceNow](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#servicenow)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "servicenow-example",
    ///         Type = "SERVICE_NOW",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "url",
    ///                 Value = "https://service-now.com/",
    ///             },
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "two_way_integration",
    ///                 Value = "true",
    ///             },
    ///         },
    ///         AuthBasic = new NewRelic.Inputs.NotificationDestinationAuthBasicArgs
    ///         {
    ///             User = "username",
    ///             Password = "password",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [Email](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#email)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "email-example",
    ///         Type = "EMAIL",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "email",
    ///                 Value = "email@email.com,email2@email.com",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [Jira](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#jira)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "jira-example",
    ///         Type = "JIRA",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "url",
    ///                 Value = "https://example.atlassian.net",
    ///             },
    ///         },
    ///         AuthBasic = new NewRelic.Inputs.NotificationDestinationAuthBasicArgs
    ///         {
    ///             User = "example@email.com",
    ///             Password = "password",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [PagerDuty with service integration](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#pagerduty-sli)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "pagerduty-service-example",
    ///         Type = "PAGERDUTY_SERVICE_INTEGRATION",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "",
    ///                 Value = "",
    ///             },
    ///         },
    ///         AuthToken = new NewRelic.Inputs.NotificationDestinationAuthTokenArgs
    ///         {
    ///             Prefix = "Token token=",
    ///             Token = "10567a689d984d03c021034b22a789e2",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ##### [PagerDuty with account integration](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#pagerduty-ali)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "pagerduty-account-example",
    ///         Type = "PAGERDUTY_ACCOUNT_INTEGRATION",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "two_way_integration",
    ///                 Value = "true",
    ///             },
    ///         },
    ///         AuthToken = new NewRelic.Inputs.NotificationDestinationAuthTokenArgs
    ///         {
    ///             Prefix = "Token token=",
    ///             Token = "u+E8EU3MhsZwLfZ1ic1A",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// #### Mobile Push
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "mobile-push-example",
    ///         Type = "MOBILE_PUSH",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "userId",
    ///                 Value = "12345678",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// #### [AWS Event Bridge](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#eventBridge)
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo", new()
    ///     {
    ///         AccountId = "12345678",
    ///         Name = "event-bridge-example",
    ///         Type = "EVENT_BRIDGE",
    ///         Properties = new[]
    ///         {
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "AWSAccountId",
    ///                 Value = "123456789123456",
    ///             },
    ///             new NewRelic.Inputs.NotificationDestinationPropertyArgs
    ///             {
    ///                 Key = "AWSRegion",
    ///                 Value = "us-east-2",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// #### [Slack](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#slack)
    /// 
    /// In order to create a Slack destination, you have to grant our application access to your workspace. This process is [based on OAuth](https://api.slack.com/authentication/oauth-v2) and can only be done through a browser.
    /// As a result, you cannot set up a Slack destination purely with Terraform code.
    /// However, if you would like to use Slack-based destinations with other resources in the New Relic Terraform Provider, the data source `newrelic.NotificationDestination` may be used to fetch the ID of the destination; alternatively, you might want to source the ID of the destination from  NerdGraph, or from the New Relic One UI.
    /// 
    /// ## Additional Information
    /// 
    /// More information about destinations integrations can be found in NewRelic [documentation](https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/).
    /// More details about the destinations API can be found [here](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-api-notifications-destinations).
    /// 
    /// ### Moving from Legacy Alert Channels to Notification Channels
    /// As stated in the documentation of this resource and `newrelic.NotificationChannel`, destinations, created using the resource `newrelic.NotificationDestination` can be paired with `newrelic.NotificationChannel` to set up channels. These resources combined, are an alternative to the legacy resource `newrelic.AlertChannel`, which is **deprecated** and will be **removed in a future major release**, as stated in the documentation of the resource.
    /// 
    /// If you're currently using `newrelic.AlertChannel` to manage channels, we **strongly recommend** migrating to these notifications-based resources at the earliest.
    /// 
    /// Please refer to the examples in this page, or this example for illustrations on setting up channels with these resources.
    /// 
    /// ## Import
    /// 
    /// &gt; **WARNING:** Slack-based destinations can only be imported and destroyed; this resource **does not** support creating and updating Slack-based destinations, owing to the reasons stated above, under the **Slack** section.
    /// 
    /// Destination id can be found in the Destinations page &gt; three dots at the right of the chosen destination &gt; copy destination id to clipboard.
    /// This example is especially useful for slack destinations which *must* be imported.
    /// 
    /// 1. Add an empty resource to your terraform file:
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using NewRelic = Pulumi.NewRelic;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var foo = new NewRelic.NotificationDestination("foo");
    /// 
    /// });
    /// ```
    /// 2. Run import command: `terraform import newrelic_notification_destination.foo &lt;destination_id&gt;`
    /// 3. Run the following command after the import successfully done and copy the information to your resource:
    ///    `terraform state show newrelic_notification_destination.foo`
    /// 4. Add `IgnoreChanges` attribute on `All` in your imported resource:
    /// </summary>
    [NewRelicResourceType("newrelic:index/notificationDestination:NotificationDestination")]
    public partial class NotificationDestination : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// Indicates whether the destination is active.
        /// </summary>
        [Output("active")]
        public Output<bool?> Active { get; private set; } = null!;

        /// <summary>
        /// A nested block that describes a basic username and password authentication credentials. Only one AuthBasic block is permitted per notification destination definition.  See Nested AuthBasic blocks below for details.
        /// </summary>
        [Output("authBasic")]
        public Output<Outputs.NotificationDestinationAuthBasic?> AuthBasic { get; private set; } = null!;

        /// <summary>
        /// A nested block that describes a custom header authentication credentials. This field is required when the destination type is WORKFLOW_AUTOMATION and optional for other destination types. Multiple blocks are permitted per notification destination definition. Nested AuthCustomHeader blocks below for details.
        /// </summary>
        [Output("authCustomHeaders")]
        public Output<ImmutableArray<Outputs.NotificationDestinationAuthCustomHeader>> AuthCustomHeaders { get; private set; } = null!;

        /// <summary>
        /// A nested block that describes a token authentication credentials. Only one AuthToken block is permitted per notification destination definition.  See Nested AuthToken blocks below for details.
        /// </summary>
        [Output("authToken")]
        public Output<Outputs.NotificationDestinationAuthToken?> AuthToken { get; private set; } = null!;

        /// <summary>
        /// The unique entity identifier of the destination in New Relic.
        /// </summary>
        [Output("guid")]
        public Output<string> Guid { get; private set; } = null!;

        /// <summary>
        /// The last time a notification was sent.
        /// </summary>
        [Output("lastSent")]
        public Output<string> LastSent { get; private set; } = null!;

        /// <summary>
        /// The name of the destination.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// A nested block that describes a notification destination property. See Nested property blocks below for details.
        /// </summary>
        [Output("properties")]
        public Output<ImmutableArray<Outputs.NotificationDestinationProperty>> Properties { get; private set; } = null!;

        /// <summary>
        /// A nested block that describes a URL that contains sensitive data at the path or parameters. Only one SecureUrl block is permitted per notification destination definition. See Nested SecureUrl blocks below for details.
        /// </summary>
        [Output("secureUrl")]
        public Output<Outputs.NotificationDestinationSecureUrl?> SecureUrl { get; private set; } = null!;

        /// <summary>
        /// The status of the destination.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// The type of destination.  One of: `EMAIL`, `SERVICE_NOW`, `SERVICE_NOW_APP`, `WEBHOOK`, `JIRA`, `MOBILE_PUSH`, `EVENT_BRIDGE`, `PAGERDUTY_ACCOUNT_INTEGRATION` or `PAGERDUTY_SERVICE_INTEGRATION`, `MICROSOFT_TEAMS`, `WORKFLOW_AUTOMATION`. The types `SLACK` and `SLACK_COLLABORATION` can only be imported, updated and destroyed (cannot be created via terraform).
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a NotificationDestination resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NotificationDestination(string name, NotificationDestinationArgs args, CustomResourceOptions? options = null)
            : base("newrelic:index/notificationDestination:NotificationDestination", name, args ?? new NotificationDestinationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NotificationDestination(string name, Input<string> id, NotificationDestinationState? state = null, CustomResourceOptions? options = null)
            : base("newrelic:index/notificationDestination:NotificationDestination", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NotificationDestination resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NotificationDestination Get(string name, Input<string> id, NotificationDestinationState? state = null, CustomResourceOptions? options = null)
        {
            return new NotificationDestination(name, id, state, options);
        }
    }

    public sealed class NotificationDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Indicates whether the destination is active.
        /// </summary>
        [Input("active")]
        public Input<bool>? Active { get; set; }

        /// <summary>
        /// A nested block that describes a basic username and password authentication credentials. Only one AuthBasic block is permitted per notification destination definition.  See Nested AuthBasic blocks below for details.
        /// </summary>
        [Input("authBasic")]
        public Input<Inputs.NotificationDestinationAuthBasicArgs>? AuthBasic { get; set; }

        [Input("authCustomHeaders")]
        private InputList<Inputs.NotificationDestinationAuthCustomHeaderArgs>? _authCustomHeaders;

        /// <summary>
        /// A nested block that describes a custom header authentication credentials. This field is required when the destination type is WORKFLOW_AUTOMATION and optional for other destination types. Multiple blocks are permitted per notification destination definition. Nested AuthCustomHeader blocks below for details.
        /// </summary>
        public InputList<Inputs.NotificationDestinationAuthCustomHeaderArgs> AuthCustomHeaders
        {
            get => _authCustomHeaders ?? (_authCustomHeaders = new InputList<Inputs.NotificationDestinationAuthCustomHeaderArgs>());
            set => _authCustomHeaders = value;
        }

        /// <summary>
        /// A nested block that describes a token authentication credentials. Only one AuthToken block is permitted per notification destination definition.  See Nested AuthToken blocks below for details.
        /// </summary>
        [Input("authToken")]
        public Input<Inputs.NotificationDestinationAuthTokenArgs>? AuthToken { get; set; }

        /// <summary>
        /// The name of the destination.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("properties", required: true)]
        private InputList<Inputs.NotificationDestinationPropertyArgs>? _properties;

        /// <summary>
        /// A nested block that describes a notification destination property. See Nested property blocks below for details.
        /// </summary>
        public InputList<Inputs.NotificationDestinationPropertyArgs> Properties
        {
            get => _properties ?? (_properties = new InputList<Inputs.NotificationDestinationPropertyArgs>());
            set => _properties = value;
        }

        /// <summary>
        /// A nested block that describes a URL that contains sensitive data at the path or parameters. Only one SecureUrl block is permitted per notification destination definition. See Nested SecureUrl blocks below for details.
        /// </summary>
        [Input("secureUrl")]
        public Input<Inputs.NotificationDestinationSecureUrlArgs>? SecureUrl { get; set; }

        /// <summary>
        /// The type of destination.  One of: `EMAIL`, `SERVICE_NOW`, `SERVICE_NOW_APP`, `WEBHOOK`, `JIRA`, `MOBILE_PUSH`, `EVENT_BRIDGE`, `PAGERDUTY_ACCOUNT_INTEGRATION` or `PAGERDUTY_SERVICE_INTEGRATION`, `MICROSOFT_TEAMS`, `WORKFLOW_AUTOMATION`. The types `SLACK` and `SLACK_COLLABORATION` can only be imported, updated and destroyed (cannot be created via terraform).
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NotificationDestinationArgs()
        {
        }
        public static new NotificationDestinationArgs Empty => new NotificationDestinationArgs();
    }

    public sealed class NotificationDestinationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Indicates whether the destination is active.
        /// </summary>
        [Input("active")]
        public Input<bool>? Active { get; set; }

        /// <summary>
        /// A nested block that describes a basic username and password authentication credentials. Only one AuthBasic block is permitted per notification destination definition.  See Nested AuthBasic blocks below for details.
        /// </summary>
        [Input("authBasic")]
        public Input<Inputs.NotificationDestinationAuthBasicGetArgs>? AuthBasic { get; set; }

        [Input("authCustomHeaders")]
        private InputList<Inputs.NotificationDestinationAuthCustomHeaderGetArgs>? _authCustomHeaders;

        /// <summary>
        /// A nested block that describes a custom header authentication credentials. This field is required when the destination type is WORKFLOW_AUTOMATION and optional for other destination types. Multiple blocks are permitted per notification destination definition. Nested AuthCustomHeader blocks below for details.
        /// </summary>
        public InputList<Inputs.NotificationDestinationAuthCustomHeaderGetArgs> AuthCustomHeaders
        {
            get => _authCustomHeaders ?? (_authCustomHeaders = new InputList<Inputs.NotificationDestinationAuthCustomHeaderGetArgs>());
            set => _authCustomHeaders = value;
        }

        /// <summary>
        /// A nested block that describes a token authentication credentials. Only one AuthToken block is permitted per notification destination definition.  See Nested AuthToken blocks below for details.
        /// </summary>
        [Input("authToken")]
        public Input<Inputs.NotificationDestinationAuthTokenGetArgs>? AuthToken { get; set; }

        /// <summary>
        /// The unique entity identifier of the destination in New Relic.
        /// </summary>
        [Input("guid")]
        public Input<string>? Guid { get; set; }

        /// <summary>
        /// The last time a notification was sent.
        /// </summary>
        [Input("lastSent")]
        public Input<string>? LastSent { get; set; }

        /// <summary>
        /// The name of the destination.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("properties")]
        private InputList<Inputs.NotificationDestinationPropertyGetArgs>? _properties;

        /// <summary>
        /// A nested block that describes a notification destination property. See Nested property blocks below for details.
        /// </summary>
        public InputList<Inputs.NotificationDestinationPropertyGetArgs> Properties
        {
            get => _properties ?? (_properties = new InputList<Inputs.NotificationDestinationPropertyGetArgs>());
            set => _properties = value;
        }

        /// <summary>
        /// A nested block that describes a URL that contains sensitive data at the path or parameters. Only one SecureUrl block is permitted per notification destination definition. See Nested SecureUrl blocks below for details.
        /// </summary>
        [Input("secureUrl")]
        public Input<Inputs.NotificationDestinationSecureUrlGetArgs>? SecureUrl { get; set; }

        /// <summary>
        /// The status of the destination.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// The type of destination.  One of: `EMAIL`, `SERVICE_NOW`, `SERVICE_NOW_APP`, `WEBHOOK`, `JIRA`, `MOBILE_PUSH`, `EVENT_BRIDGE`, `PAGERDUTY_ACCOUNT_INTEGRATION` or `PAGERDUTY_SERVICE_INTEGRATION`, `MICROSOFT_TEAMS`, `WORKFLOW_AUTOMATION`. The types `SLACK` and `SLACK_COLLABORATION` can only be imported, updated and destroyed (cannot be created via terraform).
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public NotificationDestinationState()
        {
        }
        public static new NotificationDestinationState Empty => new NotificationDestinationState();
    }
}
