// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class AlertMutingRuleConditionCondition {
    /**
     * @return The attribute on an incident. Valid values are   `accountId`, `conditionId`, `conditionName`, `conditionRunbookUrl`, `conditionType`, `entity.guid`, `nrqlEventType`, `nrqlQuery`, `policyId`, `policyName`, `product`, `tags.&lt;NAME&gt;`, `targetId`, `targetName`
     * 
     */
    private String attribute;
    /**
     * @return The operator used to combine all the MutingRuleConditions within the group. Valid values are `AND`, `OR`.
     * 
     */
    private String operator;
    /**
     * @return The value(s) to compare against the attribute&#39;s value.
     * 
     */
    private List<String> values;

    private AlertMutingRuleConditionCondition() {}
    /**
     * @return The attribute on an incident. Valid values are   `accountId`, `conditionId`, `conditionName`, `conditionRunbookUrl`, `conditionType`, `entity.guid`, `nrqlEventType`, `nrqlQuery`, `policyId`, `policyName`, `product`, `tags.&lt;NAME&gt;`, `targetId`, `targetName`
     * 
     */
    public String attribute() {
        return this.attribute;
    }
    /**
     * @return The operator used to combine all the MutingRuleConditions within the group. Valid values are `AND`, `OR`.
     * 
     */
    public String operator() {
        return this.operator;
    }
    /**
     * @return The value(s) to compare against the attribute&#39;s value.
     * 
     */
    public List<String> values() {
        return this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AlertMutingRuleConditionCondition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String attribute;
        private String operator;
        private List<String> values;
        public Builder() {}
        public Builder(AlertMutingRuleConditionCondition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attribute = defaults.attribute;
    	      this.operator = defaults.operator;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder attribute(String attribute) {
            if (attribute == null) {
              throw new MissingRequiredPropertyException("AlertMutingRuleConditionCondition", "attribute");
            }
            this.attribute = attribute;
            return this;
        }
        @CustomType.Setter
        public Builder operator(String operator) {
            if (operator == null) {
              throw new MissingRequiredPropertyException("AlertMutingRuleConditionCondition", "operator");
            }
            this.operator = operator;
            return this;
        }
        @CustomType.Setter
        public Builder values(List<String> values) {
            if (values == null) {
              throw new MissingRequiredPropertyException("AlertMutingRuleConditionCondition", "values");
            }
            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        public AlertMutingRuleConditionCondition build() {
            final var _resultValue = new AlertMutingRuleConditionCondition();
            _resultValue.attribute = attribute;
            _resultValue.operator = operator;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
