// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.newrelic.outputs.FederatedLogsPartitionHealthCheckEnd2endDataFlow;
import com.pulumi.newrelic.outputs.FederatedLogsPartitionHealthCheckQueryConnection;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FederatedLogsPartitionHealthCheck {
    private @Nullable List<FederatedLogsPartitionHealthCheckEnd2endDataFlow> end2endDataFlows;
    private @Nullable String lastUpdatedAt;
    private @Nullable List<FederatedLogsPartitionHealthCheckQueryConnection> queryConnections;

    private FederatedLogsPartitionHealthCheck() {}
    public List<FederatedLogsPartitionHealthCheckEnd2endDataFlow> end2endDataFlows() {
        return this.end2endDataFlows == null ? List.of() : this.end2endDataFlows;
    }
    public Optional<String> lastUpdatedAt() {
        return Optional.ofNullable(this.lastUpdatedAt);
    }
    public List<FederatedLogsPartitionHealthCheckQueryConnection> queryConnections() {
        return this.queryConnections == null ? List.of() : this.queryConnections;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FederatedLogsPartitionHealthCheck defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<FederatedLogsPartitionHealthCheckEnd2endDataFlow> end2endDataFlows;
        private @Nullable String lastUpdatedAt;
        private @Nullable List<FederatedLogsPartitionHealthCheckQueryConnection> queryConnections;
        public Builder() {}
        public Builder(FederatedLogsPartitionHealthCheck defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.end2endDataFlows = defaults.end2endDataFlows;
    	      this.lastUpdatedAt = defaults.lastUpdatedAt;
    	      this.queryConnections = defaults.queryConnections;
        }

        @CustomType.Setter
        public Builder end2endDataFlows(@Nullable List<FederatedLogsPartitionHealthCheckEnd2endDataFlow> end2endDataFlows) {

            this.end2endDataFlows = end2endDataFlows;
            return this;
        }
        public Builder end2endDataFlows(FederatedLogsPartitionHealthCheckEnd2endDataFlow... end2endDataFlows) {
            return end2endDataFlows(List.of(end2endDataFlows));
        }
        @CustomType.Setter
        public Builder lastUpdatedAt(@Nullable String lastUpdatedAt) {

            this.lastUpdatedAt = lastUpdatedAt;
            return this;
        }
        @CustomType.Setter
        public Builder queryConnections(@Nullable List<FederatedLogsPartitionHealthCheckQueryConnection> queryConnections) {

            this.queryConnections = queryConnections;
            return this;
        }
        public Builder queryConnections(FederatedLogsPartitionHealthCheckQueryConnection... queryConnections) {
            return queryConnections(List.of(queryConnections));
        }
        public FederatedLogsPartitionHealthCheck build() {
            final var _resultValue = new FederatedLogsPartitionHealthCheck();
            _resultValue.end2endDataFlows = end2endDataFlows;
            _resultValue.lastUpdatedAt = lastUpdatedAt;
            _resultValue.queryConnections = queryConnections;
            return _resultValue;
        }
    }
}
