// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.newrelic.outputs.FederatedLogsSetupDefaultPartitionDataRetentionPolicy;
import com.pulumi.newrelic.outputs.FederatedLogsSetupDefaultPartitionStorage;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FederatedLogsSetupDefaultPartition {
    /**
     * @return Retention policy for logs in the default partition. See below.
     * 
     */
    private @Nullable FederatedLogsSetupDefaultPartitionDataRetentionPolicy dataRetentionPolicy;
    /**
     * @return Storage details for the default partition. See below.
     * 
     */
    private FederatedLogsSetupDefaultPartitionStorage storage;

    private FederatedLogsSetupDefaultPartition() {}
    /**
     * @return Retention policy for logs in the default partition. See below.
     * 
     */
    public Optional<FederatedLogsSetupDefaultPartitionDataRetentionPolicy> dataRetentionPolicy() {
        return Optional.ofNullable(this.dataRetentionPolicy);
    }
    /**
     * @return Storage details for the default partition. See below.
     * 
     */
    public FederatedLogsSetupDefaultPartitionStorage storage() {
        return this.storage;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FederatedLogsSetupDefaultPartition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable FederatedLogsSetupDefaultPartitionDataRetentionPolicy dataRetentionPolicy;
        private FederatedLogsSetupDefaultPartitionStorage storage;
        public Builder() {}
        public Builder(FederatedLogsSetupDefaultPartition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataRetentionPolicy = defaults.dataRetentionPolicy;
    	      this.storage = defaults.storage;
        }

        @CustomType.Setter
        public Builder dataRetentionPolicy(@Nullable FederatedLogsSetupDefaultPartitionDataRetentionPolicy dataRetentionPolicy) {

            this.dataRetentionPolicy = dataRetentionPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder storage(FederatedLogsSetupDefaultPartitionStorage storage) {
            if (storage == null) {
              throw new MissingRequiredPropertyException("FederatedLogsSetupDefaultPartition", "storage");
            }
            this.storage = storage;
            return this;
        }
        public FederatedLogsSetupDefaultPartition build() {
            final var _resultValue = new FederatedLogsSetupDefaultPartition();
            _resultValue.dataRetentionPolicy = dataRetentionPolicy;
            _resultValue.storage = storage;
            return _resultValue;
        }
    }
}
