// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NrqlAlertConditionOutlierConfigurationDbscan {
    /**
     * @return BETA PREVIEW: the `epsilon` field is in limited release and only enabled for preview on a per-account basis. - Radius (distance threshold) for DBSCAN in the units of the query result. Smaller values tighten clusters; larger values broaden them. Must be &gt; 0.
     * 
     */
    private Double epsilon;
    /**
     * @return BETA PREVIEW: the `evaluationGroupFacet` field is in limited release and only enabled for preview on a per-account basis. - Optional NRQL facet attribute used to segment data into groups (e.g. `host`, `region`) before running outlier detection. Omit to evaluate all results together.
     * 
     */
    private @Nullable String evaluationGroupFacet;
    /**
     * @return BETA PREVIEW: the `minimumPoints` field is in limited release and only enabled for preview on a per-account basis. - Minimum number of neighboring points needed to form a cluster. Must be &gt;= 1.
     * 
     */
    private Integer minimumPoints;

    private NrqlAlertConditionOutlierConfigurationDbscan() {}
    /**
     * @return BETA PREVIEW: the `epsilon` field is in limited release and only enabled for preview on a per-account basis. - Radius (distance threshold) for DBSCAN in the units of the query result. Smaller values tighten clusters; larger values broaden them. Must be &gt; 0.
     * 
     */
    public Double epsilon() {
        return this.epsilon;
    }
    /**
     * @return BETA PREVIEW: the `evaluationGroupFacet` field is in limited release and only enabled for preview on a per-account basis. - Optional NRQL facet attribute used to segment data into groups (e.g. `host`, `region`) before running outlier detection. Omit to evaluate all results together.
     * 
     */
    public Optional<String> evaluationGroupFacet() {
        return Optional.ofNullable(this.evaluationGroupFacet);
    }
    /**
     * @return BETA PREVIEW: the `minimumPoints` field is in limited release and only enabled for preview on a per-account basis. - Minimum number of neighboring points needed to form a cluster. Must be &gt;= 1.
     * 
     */
    public Integer minimumPoints() {
        return this.minimumPoints;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NrqlAlertConditionOutlierConfigurationDbscan defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double epsilon;
        private @Nullable String evaluationGroupFacet;
        private Integer minimumPoints;
        public Builder() {}
        public Builder(NrqlAlertConditionOutlierConfigurationDbscan defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.epsilon = defaults.epsilon;
    	      this.evaluationGroupFacet = defaults.evaluationGroupFacet;
    	      this.minimumPoints = defaults.minimumPoints;
        }

        @CustomType.Setter
        public Builder epsilon(Double epsilon) {
            if (epsilon == null) {
              throw new MissingRequiredPropertyException("NrqlAlertConditionOutlierConfigurationDbscan", "epsilon");
            }
            this.epsilon = epsilon;
            return this;
        }
        @CustomType.Setter
        public Builder evaluationGroupFacet(@Nullable String evaluationGroupFacet) {

            this.evaluationGroupFacet = evaluationGroupFacet;
            return this;
        }
        @CustomType.Setter
        public Builder minimumPoints(Integer minimumPoints) {
            if (minimumPoints == null) {
              throw new MissingRequiredPropertyException("NrqlAlertConditionOutlierConfigurationDbscan", "minimumPoints");
            }
            this.minimumPoints = minimumPoints;
            return this;
        }
        public NrqlAlertConditionOutlierConfigurationDbscan build() {
            final var _resultValue = new NrqlAlertConditionOutlierConfigurationDbscan();
            _resultValue.epsilon = epsilon;
            _resultValue.evaluationGroupFacet = evaluationGroupFacet;
            _resultValue.minimumPoints = minimumPoints;
            return _resultValue;
        }
    }
}
