// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class CardinalityManagementMetricArgs extends com.pulumi.resources.ResourceArgs {

    public static final CardinalityManagementMetricArgs Empty = new CardinalityManagementMetricArgs();

    /**
     * The maximum number of unique dimension-value combinations allowed per day for this metric.
     * 
     */
    @Import(name="cardinalityLimit", required=true)
    private Output<Integer> cardinalityLimit;

    /**
     * @return The maximum number of unique dimension-value combinations allowed per day for this metric.
     * 
     */
    public Output<Integer> cardinalityLimit() {
        return this.cardinalityLimit;
    }

    /**
     * The full name of the metric (e.g. `&#34;http.server.duration&#34;`).
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The full name of the metric (e.g. `&#34;http.server.duration&#34;`).
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private CardinalityManagementMetricArgs() {}

    private CardinalityManagementMetricArgs(CardinalityManagementMetricArgs $) {
        this.cardinalityLimit = $.cardinalityLimit;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CardinalityManagementMetricArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CardinalityManagementMetricArgs $;

        public Builder() {
            $ = new CardinalityManagementMetricArgs();
        }

        public Builder(CardinalityManagementMetricArgs defaults) {
            $ = new CardinalityManagementMetricArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cardinalityLimit The maximum number of unique dimension-value combinations allowed per day for this metric.
         * 
         * @return builder
         * 
         */
        public Builder cardinalityLimit(Output<Integer> cardinalityLimit) {
            $.cardinalityLimit = cardinalityLimit;
            return this;
        }

        /**
         * @param cardinalityLimit The maximum number of unique dimension-value combinations allowed per day for this metric.
         * 
         * @return builder
         * 
         */
        public Builder cardinalityLimit(Integer cardinalityLimit) {
            return cardinalityLimit(Output.of(cardinalityLimit));
        }

        /**
         * @param name The full name of the metric (e.g. `&#34;http.server.duration&#34;`).
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The full name of the metric (e.g. `&#34;http.server.duration&#34;`).
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public CardinalityManagementMetricArgs build() {
            if ($.cardinalityLimit == null) {
                throw new MissingRequiredPropertyException("CardinalityManagementMetricArgs", "cardinalityLimit");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("CardinalityManagementMetricArgs", "name");
            }
            return $;
        }
    }

}
