// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNotebookPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNotebookPlainArgs Empty = new GetNotebookPlainArgs();

    /**
     * When `true`, fetches the full notebook body and populates `content`. Default: `false`.
     * 
     */
    @Import(name="fetchContent")
    private @Nullable Boolean fetchContent;

    /**
     * @return When `true`, fetches the full notebook body and populates `content`. Default: `false`.
     * 
     */
    public Optional<Boolean> fetchContent() {
        return Optional.ofNullable(this.fetchContent);
    }

    /**
     * The entity GUID of the notebook to look up.
     * 
     */
    @Import(name="guid", required=true)
    private String guid;

    /**
     * @return The entity GUID of the notebook to look up.
     * 
     */
    public String guid() {
        return this.guid;
    }

    private GetNotebookPlainArgs() {}

    private GetNotebookPlainArgs(GetNotebookPlainArgs $) {
        this.fetchContent = $.fetchContent;
        this.guid = $.guid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNotebookPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNotebookPlainArgs $;

        public Builder() {
            $ = new GetNotebookPlainArgs();
        }

        public Builder(GetNotebookPlainArgs defaults) {
            $ = new GetNotebookPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param fetchContent When `true`, fetches the full notebook body and populates `content`. Default: `false`.
         * 
         * @return builder
         * 
         */
        public Builder fetchContent(@Nullable Boolean fetchContent) {
            $.fetchContent = fetchContent;
            return this;
        }

        /**
         * @param guid The entity GUID of the notebook to look up.
         * 
         * @return builder
         * 
         */
        public Builder guid(String guid) {
            $.guid = guid;
            return this;
        }

        public GetNotebookPlainArgs build() {
            if ($.guid == null) {
                throw new MissingRequiredPropertyException("GetNotebookPlainArgs", "guid");
            }
            return $;
        }
    }

}
