// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class NotificationDestinationAuthBasicArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationDestinationAuthBasicArgs Empty = new NotificationDestinationAuthBasicArgs();

    @Import(name="password", required=true)
    private Output<String> password;

    public Output<String> password() {
        return this.password;
    }

    @Import(name="user", required=true)
    private Output<String> user;

    public Output<String> user() {
        return this.user;
    }

    private NotificationDestinationAuthBasicArgs() {}

    private NotificationDestinationAuthBasicArgs(NotificationDestinationAuthBasicArgs $) {
        this.password = $.password;
        this.user = $.user;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationDestinationAuthBasicArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationDestinationAuthBasicArgs $;

        public Builder() {
            $ = new NotificationDestinationAuthBasicArgs();
        }

        public Builder(NotificationDestinationAuthBasicArgs defaults) {
            $ = new NotificationDestinationAuthBasicArgs(Objects.requireNonNull(defaults));
        }

        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder user(Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public NotificationDestinationAuthBasicArgs build() {
            if ($.password == null) {
                throw new MissingRequiredPropertyException("NotificationDestinationAuthBasicArgs", "password");
            }
            if ($.user == null) {
                throw new MissingRequiredPropertyException("NotificationDestinationAuthBasicArgs", "user");
            }
            return $;
        }
    }

}
