// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.newrelic.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PathpointFlowStageLevelStepEntitySearchQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final PathpointFlowStageLevelStepEntitySearchQueryArgs Empty = new PathpointFlowStageLevelStepEntitySearchQueryArgs();

    /**
     * When true, this query is excluded from health calculation.
     * 
     */
    @Import(name="isExcluded")
    private @Nullable Output<Boolean> isExcluded;

    /**
     * @return When true, this query is excluded from health calculation.
     * 
     */
    public Optional<Output<Boolean>> isExcluded() {
        return Optional.ofNullable(this.isExcluded);
    }

    /**
     * Filter query for signals, e.g. domain=&#39;NR1&#39; AND type=&#39;APPLICATION&#39;.
     * 
     */
    @Import(name="query", required=true)
    private Output<String> query;

    /**
     * @return Filter query for signals, e.g. domain=&#39;NR1&#39; AND type=&#39;APPLICATION&#39;.
     * 
     */
    public Output<String> query() {
        return this.query;
    }

    private PathpointFlowStageLevelStepEntitySearchQueryArgs() {}

    private PathpointFlowStageLevelStepEntitySearchQueryArgs(PathpointFlowStageLevelStepEntitySearchQueryArgs $) {
        this.isExcluded = $.isExcluded;
        this.query = $.query;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PathpointFlowStageLevelStepEntitySearchQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PathpointFlowStageLevelStepEntitySearchQueryArgs $;

        public Builder() {
            $ = new PathpointFlowStageLevelStepEntitySearchQueryArgs();
        }

        public Builder(PathpointFlowStageLevelStepEntitySearchQueryArgs defaults) {
            $ = new PathpointFlowStageLevelStepEntitySearchQueryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param isExcluded When true, this query is excluded from health calculation.
         * 
         * @return builder
         * 
         */
        public Builder isExcluded(@Nullable Output<Boolean> isExcluded) {
            $.isExcluded = isExcluded;
            return this;
        }

        /**
         * @param isExcluded When true, this query is excluded from health calculation.
         * 
         * @return builder
         * 
         */
        public Builder isExcluded(Boolean isExcluded) {
            return isExcluded(Output.of(isExcluded));
        }

        /**
         * @param query Filter query for signals, e.g. domain=&#39;NR1&#39; AND type=&#39;APPLICATION&#39;.
         * 
         * @return builder
         * 
         */
        public Builder query(Output<String> query) {
            $.query = query;
            return this;
        }

        /**
         * @param query Filter query for signals, e.g. domain=&#39;NR1&#39; AND type=&#39;APPLICATION&#39;.
         * 
         * @return builder
         * 
         */
        public Builder query(String query) {
            return query(Output.of(query));
        }

        public PathpointFlowStageLevelStepEntitySearchQueryArgs build() {
            if ($.query == null) {
                throw new MissingRequiredPropertyException("PathpointFlowStageLevelStepEntitySearchQueryArgs", "query");
            }
            return $;
        }
    }

}
