// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-newrelic/sdk/v5/go/newrelic/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this resource to configure which GCP services New Relic polls as part of the **GCP Dimensional Metrics** integration. Each service is enabled by adding the corresponding block; omit a block to disable polling for that service.
//
// ## Prerequisite
//
// This resource requires a linked GCP account created with `cloud.GcpLinkAccount` using its keyless (WIF) mode — set `useWorkloadIdentityFederation = true` along with `audience` and `serviceAccountEmail` on that resource. See the full GCP Dimensional Metrics guide for complete setup instructions including the required GCP Workload Identity Federation infrastructure.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-newrelic/sdk/v5/go/newrelic/cloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := cloud.NewGcpLinkAccount(ctx, "example", &cloud.GcpLinkAccountArgs{
//				AccountId:                     pulumi.Any(newrelicAccountId),
//				Name:                          pulumi.String("my-gcp-project"),
//				ProjectId:                     pulumi.String("my-gcp-project-id"),
//				UseWorkloadIdentityFederation: pulumi.Bool(true),
//				Audience:                      pulumi.String("//iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID"),
//				ServiceAccountEmail:           pulumi.String("newrelic-integration@my-gcp-project-id.iam.gserviceaccount.com"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = cloud.NewGcpDmIntegrations(ctx, "example", &cloud.GcpDmIntegrationsArgs{
//				AccountId:       pulumi.Any(newrelicAccountId),
//				LinkedAccountId: example.ID(),
//				AiPlatform: &cloud.GcpDmIntegrationsAiPlatformArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				ApiGateway: &cloud.GcpDmIntegrationsApiGatewayArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				AppEngine: &cloud.GcpDmIntegrationsAppEngineArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				BigTable: &cloud.GcpDmIntegrationsBigTableArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Composer: &cloud.GcpDmIntegrationsComposerArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				DataStore: &cloud.GcpDmIntegrationsDataStoreArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseAuth: &cloud.GcpDmIntegrationsFirebaseAuthArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseDatabase: &cloud.GcpDmIntegrationsFirebaseDatabaseArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseHosting: &cloud.GcpDmIntegrationsFirebaseHostingArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseStorage: &cloud.GcpDmIntegrationsFirebaseStorageArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Firestore: &cloud.GcpDmIntegrationsFirestoreArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Functions: &cloud.GcpDmIntegrationsFunctionsArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Interconnect: &cloud.GcpDmIntegrationsInterconnectArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Istio: &cloud.GcpDmIntegrationsIstioArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Kubernetes: &cloud.GcpDmIntegrationsKubernetesArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				MemCache: &cloud.GcpDmIntegrationsMemCacheArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				MemoryStore: &cloud.GcpDmIntegrationsMemoryStoreArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Redis: &cloud.GcpDmIntegrationsRedisArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Router: &cloud.GcpDmIntegrationsRouterArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Run: &cloud.GcpDmIntegrationsRunArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				Sql: &cloud.GcpDmIntegrationsSqlArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				VirtualMachines: &cloud.GcpDmIntegrationsVirtualMachinesArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				VpcAccess: &cloud.GcpDmIntegrationsVpcAccessArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseAppHosting: &cloud.GcpDmIntegrationsFirebaseAppHostingArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				FirebaseVertexAi: &cloud.GcpDmIntegrationsFirebaseVertexAiArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//				AlloyDb: &cloud.GcpDmIntegrationsAlloyDbArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				BigQuery: &cloud.GcpDmIntegrationsBigQueryArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				DataFlow: &cloud.GcpDmIntegrationsDataFlowArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				DataProc: &cloud.GcpDmIntegrationsDataProcArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				LoadBalancing: &cloud.GcpDmIntegrationsLoadBalancingArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				ManagedKafka: &cloud.GcpDmIntegrationsManagedKafkaArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				PubSub: &cloud.GcpDmIntegrationsPubSubArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				Spanner: &cloud.GcpDmIntegrationsSpannerArgs{
//					MetricsPollingInterval: pulumi.Int(60),
//				},
//				Storage: &cloud.GcpDmIntegrationsStorageArgs{
//					MetricsPollingInterval: pulumi.Int(300),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// GCP DM integrations can be imported using the `id`:
//
// ```sh
// $ pulumi import newrelic:cloud/gcpDmIntegrations:GcpDmIntegrations example <id>
// ```
type GcpDmIntegrations struct {
	pulumi.CustomResourceState

	// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// GCP Vertex AI / AI Platform.
	AiPlatform GcpDmIntegrationsAiPlatformPtrOutput `pulumi:"aiPlatform"`
	// GCP AlloyDB.
	AlloyDb GcpDmIntegrationsAlloyDbPtrOutput `pulumi:"alloyDb"`
	// GCP API Gateway (Dimensional Metrics only).
	ApiGateway GcpDmIntegrationsApiGatewayPtrOutput `pulumi:"apiGateway"`
	// GCP App Engine.
	AppEngine GcpDmIntegrationsAppEnginePtrOutput `pulumi:"appEngine"`
	// GCP BigQuery.
	BigQuery GcpDmIntegrationsBigQueryPtrOutput `pulumi:"bigQuery"`
	// GCP Bigtable.
	BigTable GcpDmIntegrationsBigTablePtrOutput `pulumi:"bigTable"`
	// GCP Cloud Composer.
	Composer GcpDmIntegrationsComposerPtrOutput `pulumi:"composer"`
	// GCP Cloud Dataflow.
	DataFlow GcpDmIntegrationsDataFlowPtrOutput `pulumi:"dataFlow"`
	// GCP Cloud Dataproc.
	DataProc GcpDmIntegrationsDataProcPtrOutput `pulumi:"dataProc"`
	// GCP Cloud Datastore.
	DataStore GcpDmIntegrationsDataStorePtrOutput `pulumi:"dataStore"`
	// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
	FirebaseAppHosting GcpDmIntegrationsFirebaseAppHostingPtrOutput `pulumi:"firebaseAppHosting"`
	// Firebase Authentication (Dimensional Metrics only).
	FirebaseAuth GcpDmIntegrationsFirebaseAuthPtrOutput `pulumi:"firebaseAuth"`
	// GCP Firebase Realtime Database.
	FirebaseDatabase GcpDmIntegrationsFirebaseDatabasePtrOutput `pulumi:"firebaseDatabase"`
	// GCP Firebase Hosting.
	FirebaseHosting GcpDmIntegrationsFirebaseHostingPtrOutput `pulumi:"firebaseHosting"`
	// GCP Firebase Storage.
	FirebaseStorage GcpDmIntegrationsFirebaseStoragePtrOutput `pulumi:"firebaseStorage"`
	// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
	FirebaseVertexAi GcpDmIntegrationsFirebaseVertexAiPtrOutput `pulumi:"firebaseVertexAi"`
	// GCP Firestore.
	Firestore GcpDmIntegrationsFirestorePtrOutput `pulumi:"firestore"`
	// GCP Cloud Functions.
	Functions GcpDmIntegrationsFunctionsPtrOutput `pulumi:"functions"`
	// GCP Cloud Interconnect.
	Interconnect GcpDmIntegrationsInterconnectPtrOutput `pulumi:"interconnect"`
	// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
	Istio GcpDmIntegrationsIstioPtrOutput `pulumi:"istio"`
	// GCP Google Kubernetes Engine (GKE).
	Kubernetes GcpDmIntegrationsKubernetesPtrOutput `pulumi:"kubernetes"`
	// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
	LinkedAccountId pulumi.StringOutput `pulumi:"linkedAccountId"`
	// GCP Cloud Load Balancing.
	LoadBalancing GcpDmIntegrationsLoadBalancingPtrOutput `pulumi:"loadBalancing"`
	// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
	ManagedKafka GcpDmIntegrationsManagedKafkaPtrOutput `pulumi:"managedKafka"`
	// GCP Memcache.
	MemCache GcpDmIntegrationsMemCachePtrOutput `pulumi:"memCache"`
	// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
	MemoryStore GcpDmIntegrationsMemoryStorePtrOutput `pulumi:"memoryStore"`
	// GCP Cloud Pub/Sub.
	PubSub GcpDmIntegrationsPubSubPtrOutput `pulumi:"pubSub"`
	// GCP Memorystore for Redis (legacy).
	Redis GcpDmIntegrationsRedisPtrOutput `pulumi:"redis"`
	// GCP Cloud Router.
	Router GcpDmIntegrationsRouterPtrOutput `pulumi:"router"`
	// GCP Cloud Run.
	Run GcpDmIntegrationsRunPtrOutput `pulumi:"run"`
	// GCP Cloud Spanner.
	Spanner GcpDmIntegrationsSpannerPtrOutput `pulumi:"spanner"`
	// GCP Cloud SQL.
	Sql GcpDmIntegrationsSqlPtrOutput `pulumi:"sql"`
	// GCP Cloud Storage.
	Storage GcpDmIntegrationsStoragePtrOutput `pulumi:"storage"`
	// GCP Compute Engine VMs.
	VirtualMachines GcpDmIntegrationsVirtualMachinesPtrOutput `pulumi:"virtualMachines"`
	// GCP Serverless VPC Access.
	VpcAccess GcpDmIntegrationsVpcAccessPtrOutput `pulumi:"vpcAccess"`
}

// NewGcpDmIntegrations registers a new resource with the given unique name, arguments, and options.
func NewGcpDmIntegrations(ctx *pulumi.Context,
	name string, args *GcpDmIntegrationsArgs, opts ...pulumi.ResourceOption) (*GcpDmIntegrations, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.LinkedAccountId == nil {
		return nil, errors.New("invalid value for required argument 'LinkedAccountId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GcpDmIntegrations
	err := ctx.RegisterResource("newrelic:cloud/gcpDmIntegrations:GcpDmIntegrations", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGcpDmIntegrations gets an existing GcpDmIntegrations resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGcpDmIntegrations(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GcpDmIntegrationsState, opts ...pulumi.ResourceOption) (*GcpDmIntegrations, error) {
	var resource GcpDmIntegrations
	err := ctx.ReadResource("newrelic:cloud/gcpDmIntegrations:GcpDmIntegrations", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GcpDmIntegrations resources.
type gcpDmIntegrationsState struct {
	// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
	AccountId *string `pulumi:"accountId"`
	// GCP Vertex AI / AI Platform.
	AiPlatform *GcpDmIntegrationsAiPlatform `pulumi:"aiPlatform"`
	// GCP AlloyDB.
	AlloyDb *GcpDmIntegrationsAlloyDb `pulumi:"alloyDb"`
	// GCP API Gateway (Dimensional Metrics only).
	ApiGateway *GcpDmIntegrationsApiGateway `pulumi:"apiGateway"`
	// GCP App Engine.
	AppEngine *GcpDmIntegrationsAppEngine `pulumi:"appEngine"`
	// GCP BigQuery.
	BigQuery *GcpDmIntegrationsBigQuery `pulumi:"bigQuery"`
	// GCP Bigtable.
	BigTable *GcpDmIntegrationsBigTable `pulumi:"bigTable"`
	// GCP Cloud Composer.
	Composer *GcpDmIntegrationsComposer `pulumi:"composer"`
	// GCP Cloud Dataflow.
	DataFlow *GcpDmIntegrationsDataFlow `pulumi:"dataFlow"`
	// GCP Cloud Dataproc.
	DataProc *GcpDmIntegrationsDataProc `pulumi:"dataProc"`
	// GCP Cloud Datastore.
	DataStore *GcpDmIntegrationsDataStore `pulumi:"dataStore"`
	// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
	FirebaseAppHosting *GcpDmIntegrationsFirebaseAppHosting `pulumi:"firebaseAppHosting"`
	// Firebase Authentication (Dimensional Metrics only).
	FirebaseAuth *GcpDmIntegrationsFirebaseAuth `pulumi:"firebaseAuth"`
	// GCP Firebase Realtime Database.
	FirebaseDatabase *GcpDmIntegrationsFirebaseDatabase `pulumi:"firebaseDatabase"`
	// GCP Firebase Hosting.
	FirebaseHosting *GcpDmIntegrationsFirebaseHosting `pulumi:"firebaseHosting"`
	// GCP Firebase Storage.
	FirebaseStorage *GcpDmIntegrationsFirebaseStorage `pulumi:"firebaseStorage"`
	// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
	FirebaseVertexAi *GcpDmIntegrationsFirebaseVertexAi `pulumi:"firebaseVertexAi"`
	// GCP Firestore.
	Firestore *GcpDmIntegrationsFirestore `pulumi:"firestore"`
	// GCP Cloud Functions.
	Functions *GcpDmIntegrationsFunctions `pulumi:"functions"`
	// GCP Cloud Interconnect.
	Interconnect *GcpDmIntegrationsInterconnect `pulumi:"interconnect"`
	// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
	Istio *GcpDmIntegrationsIstio `pulumi:"istio"`
	// GCP Google Kubernetes Engine (GKE).
	Kubernetes *GcpDmIntegrationsKubernetes `pulumi:"kubernetes"`
	// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
	LinkedAccountId *string `pulumi:"linkedAccountId"`
	// GCP Cloud Load Balancing.
	LoadBalancing *GcpDmIntegrationsLoadBalancing `pulumi:"loadBalancing"`
	// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
	ManagedKafka *GcpDmIntegrationsManagedKafka `pulumi:"managedKafka"`
	// GCP Memcache.
	MemCache *GcpDmIntegrationsMemCache `pulumi:"memCache"`
	// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
	MemoryStore *GcpDmIntegrationsMemoryStore `pulumi:"memoryStore"`
	// GCP Cloud Pub/Sub.
	PubSub *GcpDmIntegrationsPubSub `pulumi:"pubSub"`
	// GCP Memorystore for Redis (legacy).
	Redis *GcpDmIntegrationsRedis `pulumi:"redis"`
	// GCP Cloud Router.
	Router *GcpDmIntegrationsRouter `pulumi:"router"`
	// GCP Cloud Run.
	Run *GcpDmIntegrationsRun `pulumi:"run"`
	// GCP Cloud Spanner.
	Spanner *GcpDmIntegrationsSpanner `pulumi:"spanner"`
	// GCP Cloud SQL.
	Sql *GcpDmIntegrationsSql `pulumi:"sql"`
	// GCP Cloud Storage.
	Storage *GcpDmIntegrationsStorage `pulumi:"storage"`
	// GCP Compute Engine VMs.
	VirtualMachines *GcpDmIntegrationsVirtualMachines `pulumi:"virtualMachines"`
	// GCP Serverless VPC Access.
	VpcAccess *GcpDmIntegrationsVpcAccess `pulumi:"vpcAccess"`
}

type GcpDmIntegrationsState struct {
	// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
	AccountId pulumi.StringPtrInput
	// GCP Vertex AI / AI Platform.
	AiPlatform GcpDmIntegrationsAiPlatformPtrInput
	// GCP AlloyDB.
	AlloyDb GcpDmIntegrationsAlloyDbPtrInput
	// GCP API Gateway (Dimensional Metrics only).
	ApiGateway GcpDmIntegrationsApiGatewayPtrInput
	// GCP App Engine.
	AppEngine GcpDmIntegrationsAppEnginePtrInput
	// GCP BigQuery.
	BigQuery GcpDmIntegrationsBigQueryPtrInput
	// GCP Bigtable.
	BigTable GcpDmIntegrationsBigTablePtrInput
	// GCP Cloud Composer.
	Composer GcpDmIntegrationsComposerPtrInput
	// GCP Cloud Dataflow.
	DataFlow GcpDmIntegrationsDataFlowPtrInput
	// GCP Cloud Dataproc.
	DataProc GcpDmIntegrationsDataProcPtrInput
	// GCP Cloud Datastore.
	DataStore GcpDmIntegrationsDataStorePtrInput
	// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
	FirebaseAppHosting GcpDmIntegrationsFirebaseAppHostingPtrInput
	// Firebase Authentication (Dimensional Metrics only).
	FirebaseAuth GcpDmIntegrationsFirebaseAuthPtrInput
	// GCP Firebase Realtime Database.
	FirebaseDatabase GcpDmIntegrationsFirebaseDatabasePtrInput
	// GCP Firebase Hosting.
	FirebaseHosting GcpDmIntegrationsFirebaseHostingPtrInput
	// GCP Firebase Storage.
	FirebaseStorage GcpDmIntegrationsFirebaseStoragePtrInput
	// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
	FirebaseVertexAi GcpDmIntegrationsFirebaseVertexAiPtrInput
	// GCP Firestore.
	Firestore GcpDmIntegrationsFirestorePtrInput
	// GCP Cloud Functions.
	Functions GcpDmIntegrationsFunctionsPtrInput
	// GCP Cloud Interconnect.
	Interconnect GcpDmIntegrationsInterconnectPtrInput
	// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
	Istio GcpDmIntegrationsIstioPtrInput
	// GCP Google Kubernetes Engine (GKE).
	Kubernetes GcpDmIntegrationsKubernetesPtrInput
	// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
	LinkedAccountId pulumi.StringPtrInput
	// GCP Cloud Load Balancing.
	LoadBalancing GcpDmIntegrationsLoadBalancingPtrInput
	// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
	ManagedKafka GcpDmIntegrationsManagedKafkaPtrInput
	// GCP Memcache.
	MemCache GcpDmIntegrationsMemCachePtrInput
	// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
	MemoryStore GcpDmIntegrationsMemoryStorePtrInput
	// GCP Cloud Pub/Sub.
	PubSub GcpDmIntegrationsPubSubPtrInput
	// GCP Memorystore for Redis (legacy).
	Redis GcpDmIntegrationsRedisPtrInput
	// GCP Cloud Router.
	Router GcpDmIntegrationsRouterPtrInput
	// GCP Cloud Run.
	Run GcpDmIntegrationsRunPtrInput
	// GCP Cloud Spanner.
	Spanner GcpDmIntegrationsSpannerPtrInput
	// GCP Cloud SQL.
	Sql GcpDmIntegrationsSqlPtrInput
	// GCP Cloud Storage.
	Storage GcpDmIntegrationsStoragePtrInput
	// GCP Compute Engine VMs.
	VirtualMachines GcpDmIntegrationsVirtualMachinesPtrInput
	// GCP Serverless VPC Access.
	VpcAccess GcpDmIntegrationsVpcAccessPtrInput
}

func (GcpDmIntegrationsState) ElementType() reflect.Type {
	return reflect.TypeOf((*gcpDmIntegrationsState)(nil)).Elem()
}

type gcpDmIntegrationsArgs struct {
	// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
	AccountId *string `pulumi:"accountId"`
	// GCP Vertex AI / AI Platform.
	AiPlatform *GcpDmIntegrationsAiPlatform `pulumi:"aiPlatform"`
	// GCP AlloyDB.
	AlloyDb *GcpDmIntegrationsAlloyDb `pulumi:"alloyDb"`
	// GCP API Gateway (Dimensional Metrics only).
	ApiGateway *GcpDmIntegrationsApiGateway `pulumi:"apiGateway"`
	// GCP App Engine.
	AppEngine *GcpDmIntegrationsAppEngine `pulumi:"appEngine"`
	// GCP BigQuery.
	BigQuery *GcpDmIntegrationsBigQuery `pulumi:"bigQuery"`
	// GCP Bigtable.
	BigTable *GcpDmIntegrationsBigTable `pulumi:"bigTable"`
	// GCP Cloud Composer.
	Composer *GcpDmIntegrationsComposer `pulumi:"composer"`
	// GCP Cloud Dataflow.
	DataFlow *GcpDmIntegrationsDataFlow `pulumi:"dataFlow"`
	// GCP Cloud Dataproc.
	DataProc *GcpDmIntegrationsDataProc `pulumi:"dataProc"`
	// GCP Cloud Datastore.
	DataStore *GcpDmIntegrationsDataStore `pulumi:"dataStore"`
	// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
	FirebaseAppHosting *GcpDmIntegrationsFirebaseAppHosting `pulumi:"firebaseAppHosting"`
	// Firebase Authentication (Dimensional Metrics only).
	FirebaseAuth *GcpDmIntegrationsFirebaseAuth `pulumi:"firebaseAuth"`
	// GCP Firebase Realtime Database.
	FirebaseDatabase *GcpDmIntegrationsFirebaseDatabase `pulumi:"firebaseDatabase"`
	// GCP Firebase Hosting.
	FirebaseHosting *GcpDmIntegrationsFirebaseHosting `pulumi:"firebaseHosting"`
	// GCP Firebase Storage.
	FirebaseStorage *GcpDmIntegrationsFirebaseStorage `pulumi:"firebaseStorage"`
	// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
	FirebaseVertexAi *GcpDmIntegrationsFirebaseVertexAi `pulumi:"firebaseVertexAi"`
	// GCP Firestore.
	Firestore *GcpDmIntegrationsFirestore `pulumi:"firestore"`
	// GCP Cloud Functions.
	Functions *GcpDmIntegrationsFunctions `pulumi:"functions"`
	// GCP Cloud Interconnect.
	Interconnect *GcpDmIntegrationsInterconnect `pulumi:"interconnect"`
	// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
	Istio *GcpDmIntegrationsIstio `pulumi:"istio"`
	// GCP Google Kubernetes Engine (GKE).
	Kubernetes *GcpDmIntegrationsKubernetes `pulumi:"kubernetes"`
	// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
	LinkedAccountId string `pulumi:"linkedAccountId"`
	// GCP Cloud Load Balancing.
	LoadBalancing *GcpDmIntegrationsLoadBalancing `pulumi:"loadBalancing"`
	// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
	ManagedKafka *GcpDmIntegrationsManagedKafka `pulumi:"managedKafka"`
	// GCP Memcache.
	MemCache *GcpDmIntegrationsMemCache `pulumi:"memCache"`
	// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
	MemoryStore *GcpDmIntegrationsMemoryStore `pulumi:"memoryStore"`
	// GCP Cloud Pub/Sub.
	PubSub *GcpDmIntegrationsPubSub `pulumi:"pubSub"`
	// GCP Memorystore for Redis (legacy).
	Redis *GcpDmIntegrationsRedis `pulumi:"redis"`
	// GCP Cloud Router.
	Router *GcpDmIntegrationsRouter `pulumi:"router"`
	// GCP Cloud Run.
	Run *GcpDmIntegrationsRun `pulumi:"run"`
	// GCP Cloud Spanner.
	Spanner *GcpDmIntegrationsSpanner `pulumi:"spanner"`
	// GCP Cloud SQL.
	Sql *GcpDmIntegrationsSql `pulumi:"sql"`
	// GCP Cloud Storage.
	Storage *GcpDmIntegrationsStorage `pulumi:"storage"`
	// GCP Compute Engine VMs.
	VirtualMachines *GcpDmIntegrationsVirtualMachines `pulumi:"virtualMachines"`
	// GCP Serverless VPC Access.
	VpcAccess *GcpDmIntegrationsVpcAccess `pulumi:"vpcAccess"`
}

// The set of arguments for constructing a GcpDmIntegrations resource.
type GcpDmIntegrationsArgs struct {
	// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
	AccountId pulumi.StringPtrInput
	// GCP Vertex AI / AI Platform.
	AiPlatform GcpDmIntegrationsAiPlatformPtrInput
	// GCP AlloyDB.
	AlloyDb GcpDmIntegrationsAlloyDbPtrInput
	// GCP API Gateway (Dimensional Metrics only).
	ApiGateway GcpDmIntegrationsApiGatewayPtrInput
	// GCP App Engine.
	AppEngine GcpDmIntegrationsAppEnginePtrInput
	// GCP BigQuery.
	BigQuery GcpDmIntegrationsBigQueryPtrInput
	// GCP Bigtable.
	BigTable GcpDmIntegrationsBigTablePtrInput
	// GCP Cloud Composer.
	Composer GcpDmIntegrationsComposerPtrInput
	// GCP Cloud Dataflow.
	DataFlow GcpDmIntegrationsDataFlowPtrInput
	// GCP Cloud Dataproc.
	DataProc GcpDmIntegrationsDataProcPtrInput
	// GCP Cloud Datastore.
	DataStore GcpDmIntegrationsDataStorePtrInput
	// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
	FirebaseAppHosting GcpDmIntegrationsFirebaseAppHostingPtrInput
	// Firebase Authentication (Dimensional Metrics only).
	FirebaseAuth GcpDmIntegrationsFirebaseAuthPtrInput
	// GCP Firebase Realtime Database.
	FirebaseDatabase GcpDmIntegrationsFirebaseDatabasePtrInput
	// GCP Firebase Hosting.
	FirebaseHosting GcpDmIntegrationsFirebaseHostingPtrInput
	// GCP Firebase Storage.
	FirebaseStorage GcpDmIntegrationsFirebaseStoragePtrInput
	// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
	FirebaseVertexAi GcpDmIntegrationsFirebaseVertexAiPtrInput
	// GCP Firestore.
	Firestore GcpDmIntegrationsFirestorePtrInput
	// GCP Cloud Functions.
	Functions GcpDmIntegrationsFunctionsPtrInput
	// GCP Cloud Interconnect.
	Interconnect GcpDmIntegrationsInterconnectPtrInput
	// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
	Istio GcpDmIntegrationsIstioPtrInput
	// GCP Google Kubernetes Engine (GKE).
	Kubernetes GcpDmIntegrationsKubernetesPtrInput
	// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
	LinkedAccountId pulumi.StringInput
	// GCP Cloud Load Balancing.
	LoadBalancing GcpDmIntegrationsLoadBalancingPtrInput
	// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
	ManagedKafka GcpDmIntegrationsManagedKafkaPtrInput
	// GCP Memcache.
	MemCache GcpDmIntegrationsMemCachePtrInput
	// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
	MemoryStore GcpDmIntegrationsMemoryStorePtrInput
	// GCP Cloud Pub/Sub.
	PubSub GcpDmIntegrationsPubSubPtrInput
	// GCP Memorystore for Redis (legacy).
	Redis GcpDmIntegrationsRedisPtrInput
	// GCP Cloud Router.
	Router GcpDmIntegrationsRouterPtrInput
	// GCP Cloud Run.
	Run GcpDmIntegrationsRunPtrInput
	// GCP Cloud Spanner.
	Spanner GcpDmIntegrationsSpannerPtrInput
	// GCP Cloud SQL.
	Sql GcpDmIntegrationsSqlPtrInput
	// GCP Cloud Storage.
	Storage GcpDmIntegrationsStoragePtrInput
	// GCP Compute Engine VMs.
	VirtualMachines GcpDmIntegrationsVirtualMachinesPtrInput
	// GCP Serverless VPC Access.
	VpcAccess GcpDmIntegrationsVpcAccessPtrInput
}

func (GcpDmIntegrationsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*gcpDmIntegrationsArgs)(nil)).Elem()
}

type GcpDmIntegrationsInput interface {
	pulumi.Input

	ToGcpDmIntegrationsOutput() GcpDmIntegrationsOutput
	ToGcpDmIntegrationsOutputWithContext(ctx context.Context) GcpDmIntegrationsOutput
}

func (*GcpDmIntegrations) ElementType() reflect.Type {
	return reflect.TypeOf((**GcpDmIntegrations)(nil)).Elem()
}

func (i *GcpDmIntegrations) ToGcpDmIntegrationsOutput() GcpDmIntegrationsOutput {
	return i.ToGcpDmIntegrationsOutputWithContext(context.Background())
}

func (i *GcpDmIntegrations) ToGcpDmIntegrationsOutputWithContext(ctx context.Context) GcpDmIntegrationsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpDmIntegrationsOutput)
}

// GcpDmIntegrationsArrayInput is an input type that accepts GcpDmIntegrationsArray and GcpDmIntegrationsArrayOutput values.
// You can construct a concrete instance of `GcpDmIntegrationsArrayInput` via:
//
//	GcpDmIntegrationsArray{ GcpDmIntegrationsArgs{...} }
type GcpDmIntegrationsArrayInput interface {
	pulumi.Input

	ToGcpDmIntegrationsArrayOutput() GcpDmIntegrationsArrayOutput
	ToGcpDmIntegrationsArrayOutputWithContext(context.Context) GcpDmIntegrationsArrayOutput
}

type GcpDmIntegrationsArray []GcpDmIntegrationsInput

func (GcpDmIntegrationsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GcpDmIntegrations)(nil)).Elem()
}

func (i GcpDmIntegrationsArray) ToGcpDmIntegrationsArrayOutput() GcpDmIntegrationsArrayOutput {
	return i.ToGcpDmIntegrationsArrayOutputWithContext(context.Background())
}

func (i GcpDmIntegrationsArray) ToGcpDmIntegrationsArrayOutputWithContext(ctx context.Context) GcpDmIntegrationsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpDmIntegrationsArrayOutput)
}

// GcpDmIntegrationsMapInput is an input type that accepts GcpDmIntegrationsMap and GcpDmIntegrationsMapOutput values.
// You can construct a concrete instance of `GcpDmIntegrationsMapInput` via:
//
//	GcpDmIntegrationsMap{ "key": GcpDmIntegrationsArgs{...} }
type GcpDmIntegrationsMapInput interface {
	pulumi.Input

	ToGcpDmIntegrationsMapOutput() GcpDmIntegrationsMapOutput
	ToGcpDmIntegrationsMapOutputWithContext(context.Context) GcpDmIntegrationsMapOutput
}

type GcpDmIntegrationsMap map[string]GcpDmIntegrationsInput

func (GcpDmIntegrationsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GcpDmIntegrations)(nil)).Elem()
}

func (i GcpDmIntegrationsMap) ToGcpDmIntegrationsMapOutput() GcpDmIntegrationsMapOutput {
	return i.ToGcpDmIntegrationsMapOutputWithContext(context.Background())
}

func (i GcpDmIntegrationsMap) ToGcpDmIntegrationsMapOutputWithContext(ctx context.Context) GcpDmIntegrationsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpDmIntegrationsMapOutput)
}

type GcpDmIntegrationsOutput struct{ *pulumi.OutputState }

func (GcpDmIntegrationsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GcpDmIntegrations)(nil)).Elem()
}

func (o GcpDmIntegrationsOutput) ToGcpDmIntegrationsOutput() GcpDmIntegrationsOutput {
	return o
}

func (o GcpDmIntegrationsOutput) ToGcpDmIntegrationsOutputWithContext(ctx context.Context) GcpDmIntegrationsOutput {
	return o
}

// The New Relic account ID to operate on. Defaults to the `accountId` set on the provider.
func (o GcpDmIntegrationsOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// GCP Vertex AI / AI Platform.
func (o GcpDmIntegrationsOutput) AiPlatform() GcpDmIntegrationsAiPlatformPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsAiPlatformPtrOutput { return v.AiPlatform }).(GcpDmIntegrationsAiPlatformPtrOutput)
}

// GCP AlloyDB.
func (o GcpDmIntegrationsOutput) AlloyDb() GcpDmIntegrationsAlloyDbPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsAlloyDbPtrOutput { return v.AlloyDb }).(GcpDmIntegrationsAlloyDbPtrOutput)
}

// GCP API Gateway (Dimensional Metrics only).
func (o GcpDmIntegrationsOutput) ApiGateway() GcpDmIntegrationsApiGatewayPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsApiGatewayPtrOutput { return v.ApiGateway }).(GcpDmIntegrationsApiGatewayPtrOutput)
}

// GCP App Engine.
func (o GcpDmIntegrationsOutput) AppEngine() GcpDmIntegrationsAppEnginePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsAppEnginePtrOutput { return v.AppEngine }).(GcpDmIntegrationsAppEnginePtrOutput)
}

// GCP BigQuery.
func (o GcpDmIntegrationsOutput) BigQuery() GcpDmIntegrationsBigQueryPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsBigQueryPtrOutput { return v.BigQuery }).(GcpDmIntegrationsBigQueryPtrOutput)
}

// GCP Bigtable.
func (o GcpDmIntegrationsOutput) BigTable() GcpDmIntegrationsBigTablePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsBigTablePtrOutput { return v.BigTable }).(GcpDmIntegrationsBigTablePtrOutput)
}

// GCP Cloud Composer.
func (o GcpDmIntegrationsOutput) Composer() GcpDmIntegrationsComposerPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsComposerPtrOutput { return v.Composer }).(GcpDmIntegrationsComposerPtrOutput)
}

// GCP Cloud Dataflow.
func (o GcpDmIntegrationsOutput) DataFlow() GcpDmIntegrationsDataFlowPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsDataFlowPtrOutput { return v.DataFlow }).(GcpDmIntegrationsDataFlowPtrOutput)
}

// GCP Cloud Dataproc.
func (o GcpDmIntegrationsOutput) DataProc() GcpDmIntegrationsDataProcPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsDataProcPtrOutput { return v.DataProc }).(GcpDmIntegrationsDataProcPtrOutput)
}

// GCP Cloud Datastore.
func (o GcpDmIntegrationsOutput) DataStore() GcpDmIntegrationsDataStorePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsDataStorePtrOutput { return v.DataStore }).(GcpDmIntegrationsDataStorePtrOutput)
}

// Firebase App Hosting (Dimensional Metrics only; no entity synthesis).
func (o GcpDmIntegrationsOutput) FirebaseAppHosting() GcpDmIntegrationsFirebaseAppHostingPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseAppHostingPtrOutput { return v.FirebaseAppHosting }).(GcpDmIntegrationsFirebaseAppHostingPtrOutput)
}

// Firebase Authentication (Dimensional Metrics only).
func (o GcpDmIntegrationsOutput) FirebaseAuth() GcpDmIntegrationsFirebaseAuthPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseAuthPtrOutput { return v.FirebaseAuth }).(GcpDmIntegrationsFirebaseAuthPtrOutput)
}

// GCP Firebase Realtime Database.
func (o GcpDmIntegrationsOutput) FirebaseDatabase() GcpDmIntegrationsFirebaseDatabasePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseDatabasePtrOutput { return v.FirebaseDatabase }).(GcpDmIntegrationsFirebaseDatabasePtrOutput)
}

// GCP Firebase Hosting.
func (o GcpDmIntegrationsOutput) FirebaseHosting() GcpDmIntegrationsFirebaseHostingPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseHostingPtrOutput { return v.FirebaseHosting }).(GcpDmIntegrationsFirebaseHostingPtrOutput)
}

// GCP Firebase Storage.
func (o GcpDmIntegrationsOutput) FirebaseStorage() GcpDmIntegrationsFirebaseStoragePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseStoragePtrOutput { return v.FirebaseStorage }).(GcpDmIntegrationsFirebaseStoragePtrOutput)
}

// Firebase Vertex AI (Dimensional Metrics only; no entity synthesis).
func (o GcpDmIntegrationsOutput) FirebaseVertexAi() GcpDmIntegrationsFirebaseVertexAiPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirebaseVertexAiPtrOutput { return v.FirebaseVertexAi }).(GcpDmIntegrationsFirebaseVertexAiPtrOutput)
}

// GCP Firestore.
func (o GcpDmIntegrationsOutput) Firestore() GcpDmIntegrationsFirestorePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFirestorePtrOutput { return v.Firestore }).(GcpDmIntegrationsFirestorePtrOutput)
}

// GCP Cloud Functions.
func (o GcpDmIntegrationsOutput) Functions() GcpDmIntegrationsFunctionsPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsFunctionsPtrOutput { return v.Functions }).(GcpDmIntegrationsFunctionsPtrOutput)
}

// GCP Cloud Interconnect.
func (o GcpDmIntegrationsOutput) Interconnect() GcpDmIntegrationsInterconnectPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsInterconnectPtrOutput { return v.Interconnect }).(GcpDmIntegrationsInterconnectPtrOutput)
}

// GCP Istio Service Mesh (Dimensional Metrics only; no entity synthesis).
func (o GcpDmIntegrationsOutput) Istio() GcpDmIntegrationsIstioPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsIstioPtrOutput { return v.Istio }).(GcpDmIntegrationsIstioPtrOutput)
}

// GCP Google Kubernetes Engine (GKE).
func (o GcpDmIntegrationsOutput) Kubernetes() GcpDmIntegrationsKubernetesPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsKubernetesPtrOutput { return v.Kubernetes }).(GcpDmIntegrationsKubernetesPtrOutput)
}

// The ID of the linked GCP account created by `cloud.GcpLinkAccount` (in keyless/WIF mode).
func (o GcpDmIntegrationsOutput) LinkedAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) pulumi.StringOutput { return v.LinkedAccountId }).(pulumi.StringOutput)
}

// GCP Cloud Load Balancing.
func (o GcpDmIntegrationsOutput) LoadBalancing() GcpDmIntegrationsLoadBalancingPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsLoadBalancingPtrOutput { return v.LoadBalancing }).(GcpDmIntegrationsLoadBalancingPtrOutput)
}

// GCP Managed Service for Apache Kafka (Dimensional Metrics only).
func (o GcpDmIntegrationsOutput) ManagedKafka() GcpDmIntegrationsManagedKafkaPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsManagedKafkaPtrOutput { return v.ManagedKafka }).(GcpDmIntegrationsManagedKafkaPtrOutput)
}

// GCP Memcache.
func (o GcpDmIntegrationsOutput) MemCache() GcpDmIntegrationsMemCachePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsMemCachePtrOutput { return v.MemCache }).(GcpDmIntegrationsMemCachePtrOutput)
}

// GCP Memorystore for Redis/Memcached (Dimensional Metrics only).
func (o GcpDmIntegrationsOutput) MemoryStore() GcpDmIntegrationsMemoryStorePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsMemoryStorePtrOutput { return v.MemoryStore }).(GcpDmIntegrationsMemoryStorePtrOutput)
}

// GCP Cloud Pub/Sub.
func (o GcpDmIntegrationsOutput) PubSub() GcpDmIntegrationsPubSubPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsPubSubPtrOutput { return v.PubSub }).(GcpDmIntegrationsPubSubPtrOutput)
}

// GCP Memorystore for Redis (legacy).
func (o GcpDmIntegrationsOutput) Redis() GcpDmIntegrationsRedisPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsRedisPtrOutput { return v.Redis }).(GcpDmIntegrationsRedisPtrOutput)
}

// GCP Cloud Router.
func (o GcpDmIntegrationsOutput) Router() GcpDmIntegrationsRouterPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsRouterPtrOutput { return v.Router }).(GcpDmIntegrationsRouterPtrOutput)
}

// GCP Cloud Run.
func (o GcpDmIntegrationsOutput) Run() GcpDmIntegrationsRunPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsRunPtrOutput { return v.Run }).(GcpDmIntegrationsRunPtrOutput)
}

// GCP Cloud Spanner.
func (o GcpDmIntegrationsOutput) Spanner() GcpDmIntegrationsSpannerPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsSpannerPtrOutput { return v.Spanner }).(GcpDmIntegrationsSpannerPtrOutput)
}

// GCP Cloud SQL.
func (o GcpDmIntegrationsOutput) Sql() GcpDmIntegrationsSqlPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsSqlPtrOutput { return v.Sql }).(GcpDmIntegrationsSqlPtrOutput)
}

// GCP Cloud Storage.
func (o GcpDmIntegrationsOutput) Storage() GcpDmIntegrationsStoragePtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsStoragePtrOutput { return v.Storage }).(GcpDmIntegrationsStoragePtrOutput)
}

// GCP Compute Engine VMs.
func (o GcpDmIntegrationsOutput) VirtualMachines() GcpDmIntegrationsVirtualMachinesPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsVirtualMachinesPtrOutput { return v.VirtualMachines }).(GcpDmIntegrationsVirtualMachinesPtrOutput)
}

// GCP Serverless VPC Access.
func (o GcpDmIntegrationsOutput) VpcAccess() GcpDmIntegrationsVpcAccessPtrOutput {
	return o.ApplyT(func(v *GcpDmIntegrations) GcpDmIntegrationsVpcAccessPtrOutput { return v.VpcAccess }).(GcpDmIntegrationsVpcAccessPtrOutput)
}

type GcpDmIntegrationsArrayOutput struct{ *pulumi.OutputState }

func (GcpDmIntegrationsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GcpDmIntegrations)(nil)).Elem()
}

func (o GcpDmIntegrationsArrayOutput) ToGcpDmIntegrationsArrayOutput() GcpDmIntegrationsArrayOutput {
	return o
}

func (o GcpDmIntegrationsArrayOutput) ToGcpDmIntegrationsArrayOutputWithContext(ctx context.Context) GcpDmIntegrationsArrayOutput {
	return o
}

func (o GcpDmIntegrationsArrayOutput) Index(i pulumi.IntInput) GcpDmIntegrationsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GcpDmIntegrations {
		return vs[0].([]*GcpDmIntegrations)[vs[1].(int)]
	}).(GcpDmIntegrationsOutput)
}

type GcpDmIntegrationsMapOutput struct{ *pulumi.OutputState }

func (GcpDmIntegrationsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GcpDmIntegrations)(nil)).Elem()
}

func (o GcpDmIntegrationsMapOutput) ToGcpDmIntegrationsMapOutput() GcpDmIntegrationsMapOutput {
	return o
}

func (o GcpDmIntegrationsMapOutput) ToGcpDmIntegrationsMapOutputWithContext(ctx context.Context) GcpDmIntegrationsMapOutput {
	return o
}

func (o GcpDmIntegrationsMapOutput) MapIndex(k pulumi.StringInput) GcpDmIntegrationsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GcpDmIntegrations {
		return vs[0].(map[string]*GcpDmIntegrations)[vs[1].(string)]
	}).(GcpDmIntegrationsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GcpDmIntegrationsInput)(nil)).Elem(), &GcpDmIntegrations{})
	pulumi.RegisterInputType(reflect.TypeOf((*GcpDmIntegrationsArrayInput)(nil)).Elem(), GcpDmIntegrationsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GcpDmIntegrationsMapInput)(nil)).Elem(), GcpDmIntegrationsMap{})
	pulumi.RegisterOutputType(GcpDmIntegrationsOutput{})
	pulumi.RegisterOutputType(GcpDmIntegrationsArrayOutput{})
	pulumi.RegisterOutputType(GcpDmIntegrationsMapOutput{})
}
