// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Outputs
{

    [OutputType]
    public sealed class AwsConnectionSetting
    {
        /// <summary>
        /// The setting key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The setting value.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private AwsConnectionSetting(
            string key,

            string value)
        {
            Key = key;
            Value = value;
        }
    }
}
