// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Outputs
{

    [OutputType]
    public sealed class FleetDeploymentAgent
    {
        /// <summary>
        /// The agent type. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`.
        /// </summary>
        public readonly string AgentType;
        /// <summary>
        /// The entity GUID of the configuration version (from `newrelic.FleetConfiguration`) to associate with this agent. Reference `LatestVersionEntityId` to follow the current version, or `version_entity_ids[N]` to pin to a specific historical version.
        /// </summary>
        public readonly string ConfigurationVersionId;
        /// <summary>
        /// The agent version string to deploy (e.g. `"1.58.0"`).
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private FleetDeploymentAgent(
            string agentType,

            string configurationVersionId,

            string version)
        {
            AgentType = agentType;
            ConfigurationVersionId = configurationVersionId;
            Version = version;
        }
    }
}
