// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Outputs
{

    [OutputType]
    public sealed class NrqlAlertConditionOutlierConfigurationDbscan
    {
        /// <summary>
        /// BETA PREVIEW: the `Epsilon` field is in limited release and only enabled for preview on a per-account basis. - Radius (distance threshold) for DBSCAN in the units of the query result. Smaller values tighten clusters; larger values broaden them. Must be &gt; 0.
        /// </summary>
        public readonly double Epsilon;
        /// <summary>
        /// BETA PREVIEW: the `EvaluationGroupFacet` field is in limited release and only enabled for preview on a per-account basis. - Optional NRQL facet attribute used to segment data into groups (e.g. `Host`, `Region`) before running outlier detection. Omit to evaluate all results together.
        /// </summary>
        public readonly string? EvaluationGroupFacet;
        /// <summary>
        /// BETA PREVIEW: the `MinimumPoints` field is in limited release and only enabled for preview on a per-account basis. - Minimum number of neighboring points needed to form a cluster. Must be &gt;= 1.
        /// </summary>
        public readonly int MinimumPoints;

        [OutputConstructor]
        private NrqlAlertConditionOutlierConfigurationDbscan(
            double epsilon,

            string? evaluationGroupFacet,

            int minimumPoints)
        {
            Epsilon = epsilon;
            EvaluationGroupFacet = evaluationGroupFacet;
            MinimumPoints = minimumPoints;
        }
    }
}
