// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Outputs
{

    [OutputType]
    public sealed class OneDashboardPageWidgetBarColor
    {
        /// <summary>
        /// (Optional) Choose a color to customize the color of your charts per series in area, bar, line, pie, and stacked bar charts. Accepted values are RGB, HEX, or HSL code.
        /// </summary>
        public readonly string? Color;
        /// <summary>
        /// (Optional) A Nested block which will take two string attributes `Color` and `SeriesName`. This nested block is used to customize colors of individual.
        /// </summary>
        public readonly ImmutableArray<Outputs.OneDashboardPageWidgetBarColorSeriesOverride> SeriesOverrides;

        [OutputConstructor]
        private OneDashboardPageWidgetBarColor(
            string? color,

            ImmutableArray<Outputs.OneDashboardPageWidgetBarColorSeriesOverride> seriesOverrides)
        {
            Color = color;
            SeriesOverrides = seriesOverrides;
        }
    }
}
