// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Outputs
{

    [OutputType]
    public sealed class WorkflowDestination
    {
        /// <summary>
        /// id of a notification_channel to use for notifications. Please note that you have to use a 
        /// **notification** channel, not an `alert_channel`.
        /// </summary>
        public readonly string ChannelId;
        /// <summary>
        /// A nrql enrichment name. This name can be used in your notification templates (see notification_channel documentation)
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Type of the filter. Please just set this field to `FILTER`. The field is likely to be deprecated/removed in the near future.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private WorkflowDestination(
            string channelId,

            string? name,

            string? type)
        {
            ChannelId = channelId;
            Name = name;
            Type = type;
        }
    }
}
