// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NewRelic.Inputs
{

    public sealed class FederatedLogsPartitionForwarderConfigurationPipelineControlArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rule that determines which logs are routed to this partition. See below.
        /// </summary>
        [Input("partitionRule")]
        public Input<Inputs.FederatedLogsPartitionForwarderConfigurationPipelineControlPartitionRuleArgs>? PartitionRule { get; set; }

        public FederatedLogsPartitionForwarderConfigurationPipelineControlArgs()
        {
        }
        public static new FederatedLogsPartitionForwarderConfigurationPipelineControlArgs Empty => new FederatedLogsPartitionForwarderConfigurationPipelineControlArgs();
    }
}
