// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this resource to create and manage New Relic fleet configurations for centralized agent management.
 *
 * A fleet configuration holds versioned agent settings. The configuration content is immutable — each change to `configurationContent` creates a new version on the API automatically, similar to how AWS launch templates work. The resource ID (the configuration entity GUID) never changes across updates. Use the `newrelic.FleetConfiguration` data source to access the content of a specific historical version.
 *
 * ## Example Usage
 *
 * ### Basic Infrastructure Agent Configuration
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as newrelic from "@pulumi/newrelic";
 *
 * const infra = new newrelic.FleetConfiguration("infra", {
 *     name: "Production Infrastructure Config",
 *     agentType: "NRInfra",
 *     managedEntityType: "HOST",
 *     operatingSystem: "LINUX",
 *     configurationContent: `log:
 *   level: info
 *   file: /var/log/newrelic-infra/newrelic-infra.log
 * metrics:
 *   enabled: true
 *   system_sample_rate: 15
 * `,
 * });
 * ```
 *
 * ## Out-of-band drift warnings
 *
 * If a version is deleted outside of Terraform (UI, API, or another tool), the next `plan` or `refresh` will surface a warning so you understand why state changed:
 *
 * If the previously-tracked **latest** version was the one deleted, an additional, stronger warning fires explaining that `configurationContent` has been refreshed from the new latest version on the API. If your declared content differs from that new latest, the next `apply` will create a new version restoring your declared content — this is the expected, self-healing behavior.
 *
 * ## Import
 *
 * Fleet configurations can be imported using a composite ID of `<configuration_guid>:<managed_entity_type>`:
 *
 * ```sh
 * $ pulumi import newrelic:index/fleetConfiguration:FleetConfiguration infra <configuration_guid>:HOST
 * $ pulumi import newrelic:index/fleetConfiguration:FleetConfiguration infra <configuration_guid>:KUBERNETESCLUSTER
 * ```
 *
 * The `managedEntityType` portion is required because the New Relic API does not return it via the entity lookup query (a GraphQL schema constraint). All other attributes — `name`, `agentType`, `operatingSystem`, `organizationId`, `configurationContent` — are resolved automatically from the API.
 */
export class FleetConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing FleetConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FleetConfigurationState, opts?: pulumi.CustomResourceOptions): FleetConfiguration {
        return new FleetConfiguration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'newrelic:index/fleetConfiguration:FleetConfiguration';

    /**
     * Returns true if the given object is an instance of FleetConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FleetConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FleetConfiguration.__pulumiType;
    }

    /**
     * The type of agent this configuration is for. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`. **Cannot be changed after creation.**
     */
    declare public readonly agentType: pulumi.Output<string>;
    /**
     * The YAML or JSON content for this configuration. Use `file()` to load content from a file. Each change to this field creates a new immutable version on the API; the resource ID remains constant.
     */
    declare public readonly configurationContent: pulumi.Output<string>;
    /**
     * The entity GUID of the configuration.
     */
    declare public /*out*/ readonly configurationId: pulumi.Output<string>;
    /**
     * The entity GUID of the highest-numbered version.
     */
    declare public /*out*/ readonly latestVersionEntityId: pulumi.Output<string>;
    /**
     * The highest version number across all versions created so far.
     */
    declare public /*out*/ readonly latestVersionNumber: pulumi.Output<number>;
    /**
     * The type of entities this configuration manages. Valid values: `HOST`, `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    declare public readonly managedEntityType: pulumi.Output<string>;
    /**
     * The name of the configuration. **Changing this forces resource recreation** — the API does not support renaming a configuration in place.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The operating system this configuration targets. Valid values: `LINUX`, `WINDOWS`. Applicable to `HOST` configurations only — must not be set when `managedEntityType` is `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    declare public readonly operatingSystem: pulumi.Output<string | undefined>;
    /**
     * The organization ID. Auto-fetched from the account when not provided. **Cannot be changed after creation.**
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * Total number of versions currently in the configuration.
     */
    declare public /*out*/ readonly totalVersions: pulumi.Output<number>;
    /**
     * A list of entity GUIDs for all versions, sorted oldest-first. Use with the `newrelic.FleetConfiguration` data source to retrieve the content of a specific historical version.
     */
    declare public /*out*/ readonly versionEntityIds: pulumi.Output<string[]>;

    /**
     * Create a FleetConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FleetConfigurationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FleetConfigurationArgs | FleetConfigurationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FleetConfigurationState | undefined;
            resourceInputs["agentType"] = state?.agentType;
            resourceInputs["configurationContent"] = state?.configurationContent;
            resourceInputs["configurationId"] = state?.configurationId;
            resourceInputs["latestVersionEntityId"] = state?.latestVersionEntityId;
            resourceInputs["latestVersionNumber"] = state?.latestVersionNumber;
            resourceInputs["managedEntityType"] = state?.managedEntityType;
            resourceInputs["name"] = state?.name;
            resourceInputs["operatingSystem"] = state?.operatingSystem;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["totalVersions"] = state?.totalVersions;
            resourceInputs["versionEntityIds"] = state?.versionEntityIds;
        } else {
            const args = argsOrState as FleetConfigurationArgs | undefined;
            if (args?.agentType === undefined && !opts.urn) {
                throw new Error("Missing required property 'agentType'");
            }
            if (args?.configurationContent === undefined && !opts.urn) {
                throw new Error("Missing required property 'configurationContent'");
            }
            if (args?.managedEntityType === undefined && !opts.urn) {
                throw new Error("Missing required property 'managedEntityType'");
            }
            resourceInputs["agentType"] = args?.agentType;
            resourceInputs["configurationContent"] = args?.configurationContent;
            resourceInputs["managedEntityType"] = args?.managedEntityType;
            resourceInputs["name"] = args?.name;
            resourceInputs["operatingSystem"] = args?.operatingSystem;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["configurationId"] = undefined /*out*/;
            resourceInputs["latestVersionEntityId"] = undefined /*out*/;
            resourceInputs["latestVersionNumber"] = undefined /*out*/;
            resourceInputs["totalVersions"] = undefined /*out*/;
            resourceInputs["versionEntityIds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FleetConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FleetConfiguration resources.
 */
export interface FleetConfigurationState {
    /**
     * The type of agent this configuration is for. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`. **Cannot be changed after creation.**
     */
    agentType?: pulumi.Input<string | undefined>;
    /**
     * The YAML or JSON content for this configuration. Use `file()` to load content from a file. Each change to this field creates a new immutable version on the API; the resource ID remains constant.
     */
    configurationContent?: pulumi.Input<string | undefined>;
    /**
     * The entity GUID of the configuration.
     */
    configurationId?: pulumi.Input<string | undefined>;
    /**
     * The entity GUID of the highest-numbered version.
     */
    latestVersionEntityId?: pulumi.Input<string | undefined>;
    /**
     * The highest version number across all versions created so far.
     */
    latestVersionNumber?: pulumi.Input<number | undefined>;
    /**
     * The type of entities this configuration manages. Valid values: `HOST`, `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    managedEntityType?: pulumi.Input<string | undefined>;
    /**
     * The name of the configuration. **Changing this forces resource recreation** — the API does not support renaming a configuration in place.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The operating system this configuration targets. Valid values: `LINUX`, `WINDOWS`. Applicable to `HOST` configurations only — must not be set when `managedEntityType` is `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    operatingSystem?: pulumi.Input<string | undefined>;
    /**
     * The organization ID. Auto-fetched from the account when not provided. **Cannot be changed after creation.**
     */
    organizationId?: pulumi.Input<string | undefined>;
    /**
     * Total number of versions currently in the configuration.
     */
    totalVersions?: pulumi.Input<number | undefined>;
    /**
     * A list of entity GUIDs for all versions, sorted oldest-first. Use with the `newrelic.FleetConfiguration` data source to retrieve the content of a specific historical version.
     */
    versionEntityIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a FleetConfiguration resource.
 */
export interface FleetConfigurationArgs {
    /**
     * The type of agent this configuration is for. Valid values: `NRInfra`, `NRDOT`, `FluentBit`, `NRPrometheusAgent`. **Cannot be changed after creation.**
     */
    agentType: pulumi.Input<string>;
    /**
     * The YAML or JSON content for this configuration. Use `file()` to load content from a file. Each change to this field creates a new immutable version on the API; the resource ID remains constant.
     */
    configurationContent: pulumi.Input<string>;
    /**
     * The type of entities this configuration manages. Valid values: `HOST`, `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    managedEntityType: pulumi.Input<string>;
    /**
     * The name of the configuration. **Changing this forces resource recreation** — the API does not support renaming a configuration in place.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The operating system this configuration targets. Valid values: `LINUX`, `WINDOWS`. Applicable to `HOST` configurations only — must not be set when `managedEntityType` is `KUBERNETESCLUSTER`. **Cannot be changed after creation.**
     */
    operatingSystem?: pulumi.Input<string | undefined>;
    /**
     * The organization ID. Auto-fetched from the account when not provided. **Cannot be changed after creation.**
     */
    organizationId?: pulumi.Input<string | undefined>;
}
