// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NotificationDestination extends pulumi.CustomResource {
    /**
     * Get an existing NotificationDestination resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NotificationDestinationState, opts?: pulumi.CustomResourceOptions): NotificationDestination {
        return new NotificationDestination(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'newrelic:index/notificationDestination:NotificationDestination';

    /**
     * Returns true if the given object is an instance of NotificationDestination.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationDestination {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationDestination.__pulumiType;
    }

    /**
     * Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
     */
    public readonly accountId!: pulumi.Output<number>;
    /**
     * Indicates whether the destination is active.
     */
    public readonly active!: pulumi.Output<boolean | undefined>;
    /**
     * A nested block that describes a basic username and password authentication credentials. Only one authBasic block is permitted per notification destination definition.  See Nested authBasic blocks below for details.
     */
    public readonly authBasic!: pulumi.Output<outputs.NotificationDestinationAuthBasic | undefined>;
    /**
     * A nested block that describes a token authentication credentials. Only one authToken block is permitted per notification destination definition.  See Nested authToken blocks below for details.
     */
    public readonly authToken!: pulumi.Output<outputs.NotificationDestinationAuthToken | undefined>;
    /**
     * The last time a notification was sent.
     */
    public /*out*/ readonly lastSent!: pulumi.Output<string>;
    /**
     * The name of the destination.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A nested block that describes a notification destination property. See Nested property blocks below for details.
     */
    public readonly properties!: pulumi.Output<outputs.NotificationDestinationProperty[]>;
    /**
     * The status of the destination.
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * (Required) The type of the destination. One of: (WEBHOOK, EMAIL, SERVICE_NOW, PAGERDUTY_ACCOUNT_INTEGRATION,
     * PAGERDUTY_SERVICE_INTEGRATION, JIRA, SLACK, SLACK_COLLABORATION, SLACK_LEGACY, MOBILE_PUSH, EVENT_BRIDGE).
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a NotificationDestination resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NotificationDestinationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NotificationDestinationArgs | NotificationDestinationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NotificationDestinationState | undefined;
            resourceInputs["accountId"] = state ? state.accountId : undefined;
            resourceInputs["active"] = state ? state.active : undefined;
            resourceInputs["authBasic"] = state ? state.authBasic : undefined;
            resourceInputs["authToken"] = state ? state.authToken : undefined;
            resourceInputs["lastSent"] = state ? state.lastSent : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["properties"] = state ? state.properties : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as NotificationDestinationArgs | undefined;
            if ((!args || args.properties === undefined) && !opts.urn) {
                throw new Error("Missing required property 'properties'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["accountId"] = args ? args.accountId : undefined;
            resourceInputs["active"] = args ? args.active : undefined;
            resourceInputs["authBasic"] = args ? args.authBasic : undefined;
            resourceInputs["authToken"] = args ? args.authToken : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["properties"] = args ? args.properties : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["lastSent"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NotificationDestination.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NotificationDestination resources.
 */
export interface NotificationDestinationState {
    /**
     * Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
     */
    accountId?: pulumi.Input<number>;
    /**
     * Indicates whether the destination is active.
     */
    active?: pulumi.Input<boolean>;
    /**
     * A nested block that describes a basic username and password authentication credentials. Only one authBasic block is permitted per notification destination definition.  See Nested authBasic blocks below for details.
     */
    authBasic?: pulumi.Input<inputs.NotificationDestinationAuthBasic>;
    /**
     * A nested block that describes a token authentication credentials. Only one authToken block is permitted per notification destination definition.  See Nested authToken blocks below for details.
     */
    authToken?: pulumi.Input<inputs.NotificationDestinationAuthToken>;
    /**
     * The last time a notification was sent.
     */
    lastSent?: pulumi.Input<string>;
    /**
     * The name of the destination.
     */
    name?: pulumi.Input<string>;
    /**
     * A nested block that describes a notification destination property. See Nested property blocks below for details.
     */
    properties?: pulumi.Input<pulumi.Input<inputs.NotificationDestinationProperty>[]>;
    /**
     * The status of the destination.
     */
    status?: pulumi.Input<string>;
    /**
     * (Required) The type of the destination. One of: (WEBHOOK, EMAIL, SERVICE_NOW, PAGERDUTY_ACCOUNT_INTEGRATION,
     * PAGERDUTY_SERVICE_INTEGRATION, JIRA, SLACK, SLACK_COLLABORATION, SLACK_LEGACY, MOBILE_PUSH, EVENT_BRIDGE).
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NotificationDestination resource.
 */
export interface NotificationDestinationArgs {
    /**
     * Determines the New Relic account where the notification destination will be created. Defaults to the account associated with the API key used.
     */
    accountId?: pulumi.Input<number>;
    /**
     * Indicates whether the destination is active.
     */
    active?: pulumi.Input<boolean>;
    /**
     * A nested block that describes a basic username and password authentication credentials. Only one authBasic block is permitted per notification destination definition.  See Nested authBasic blocks below for details.
     */
    authBasic?: pulumi.Input<inputs.NotificationDestinationAuthBasic>;
    /**
     * A nested block that describes a token authentication credentials. Only one authToken block is permitted per notification destination definition.  See Nested authToken blocks below for details.
     */
    authToken?: pulumi.Input<inputs.NotificationDestinationAuthToken>;
    /**
     * The name of the destination.
     */
    name?: pulumi.Input<string>;
    /**
     * A nested block that describes a notification destination property. See Nested property blocks below for details.
     */
    properties: pulumi.Input<pulumi.Input<inputs.NotificationDestinationProperty>[]>;
    /**
     * (Required) The type of the destination. One of: (WEBHOOK, EMAIL, SERVICE_NOW, PAGERDUTY_ACCOUNT_INTEGRATION,
     * PAGERDUTY_SERVICE_INTEGRATION, JIRA, SLACK, SLACK_COLLABORATION, SLACK_LEGACY, MOBILE_PUSH, EVENT_BRIDGE).
     */
    type: pulumi.Input<string>;
}
